import {Search, SlidersHorizontal, ChevronLeft, ChevronRight, ChevronsUpDown, RotateCcw} from 'lucide-react';
import {forwardRef, useId, type ComponentPropsWithoutRef, type ReactNode, type Ref} from 'react';

export type StatusValue = 'ready' | 'loading' | 'running' | 'queued' | 'completed' | 'failed' | 'partial' | 'cancelled' | 'unavailable' | 'disconnected' | 'unsupported' | 'no-result';
type Tone = 'neutral' | 'info' | 'success' | 'warning' | 'error' | 'research' | 'quantum';

function cx(...names: Array<string | false | null | undefined>) { return names.filter(Boolean).join(' '); }

export function Stack({children, gap = 'md', className = ''}: {children: ReactNode; gap?: 'sm' | 'md' | 'lg'; className?: string}) { return <div className={cx('qh-stack', `qh-stack-${gap}`, className)}>{children}</div>; }
export function Cluster({children, gap = 'sm', align = 'center', className = ''}: {children: ReactNode; gap?: 'sm' | 'md' | 'lg'; align?: 'start' | 'center' | 'end'; className?: string}) { return <div className={cx('qh-cluster', `qh-cluster-${gap}`, `qh-cluster-${align}`, className)}>{children}</div>; }
export function Panel({children, variant = 'standard', as: Component = 'section', className = ''}: {children: ReactNode; variant?: 'standard' | 'subtle' | 'elevated' | 'bordered' | 'interactive'; as?: 'div' | 'section' | 'article'; className?: string}) { return <Component className={cx('qh-panel', `qh-panel-${variant}`, className)}>{children}</Component>; }
export function Section({eyebrow, title, description, actions, children, className = ''}: {eyebrow?: string; title?: string; description?: string; actions?: ReactNode; children: ReactNode; className?: string}) { return <section className={cx('qh-section', className)}><header className="qh-section-header"> <div>{eyebrow && <p className="qh-eyebrow">{eyebrow}</p>}{title && <h2>{title}</h2>}{description && <p className="qh-section-description">{description}</p>}</div>{actions && <div className="qh-section-actions">{actions}</div>}</header>{children}</section>; }
export function PageHeader({eyebrow, title, description, breadcrumb, actions}: {eyebrow?: string; title: string; description?: string; breadcrumb?: ReactNode; actions?: ReactNode}) { return <header className="qh-page-header">{breadcrumb && <div className="qh-page-breadcrumb">{breadcrumb}</div>}<div className="qh-page-header-row"><div>{eyebrow && <p className="qh-eyebrow">{eyebrow}</p>}<h1>{title}</h1>{description && <p>{description}</p>}</div>{actions && <Cluster>{actions}</Cluster>}</div></header>; }
export function Breadcrumb({items}: {items: Array<{label: string; href?: string}>}) { return <nav aria-label="Breadcrumb"><ol className="qh-breadcrumb">{items.map((item, index) => <li key={`${item.label}-${index}`}>{item.href ? <a href={item.href}>{item.label}</a> : <span aria-current="page">{item.label}</span>}{index < items.length - 1 && <ChevronRight size={13} aria-hidden="true"/>}</li>)}</ol></nav>; }

export const Input = forwardRef<HTMLInputElement, ComponentPropsWithoutRef<'input'> & {label?: string; description?: string; error?: string}>(function Input({label, description, error, id, className = '', ...props}, ref) { const generated = useId(); const inputId = id ?? generated; const helpId = description ? `${inputId}-help` : undefined; const errorId = error ? `${inputId}-error` : undefined; return <div className={cx('qh-field', error && 'is-invalid', className)}>{label && <label htmlFor={inputId}>{label}{props.required && <span aria-hidden="true"> *</span>}</label>}<input ref={ref} id={inputId} aria-describedby={cx(helpId, errorId) || undefined} aria-invalid={error ? true : undefined} {...props}/>{description && <small id={helpId}>{description}</small>}{error && <small id={errorId} className="qh-field-error" role="alert">{error}</small>}</div>; });
export function SelectField({label, description, error, options, id, ...props}: ComponentPropsWithoutRef<'select'> & {label?: string; description?: string; error?: string; options?: Array<{value: string; label: string}>}) { const generated = useId(); const selectId = id ?? generated; return <div className={cx('qh-field', error && 'is-invalid')}><label htmlFor={selectId}>{label}</label><select id={selectId} aria-invalid={error ? true : undefined} {...props}>{options?.map(option => <option key={option.value} value={option.value}>{option.label}</option>)}</select>{description && <small>{description}</small>}{error && <small className="qh-field-error" role="alert">{error}</small>}</div>; }
export function TextareaField({label, description, error, id, ...props}: ComponentPropsWithoutRef<'textarea'> & {label?: string; description?: string; error?: string}) { const generated = useId(); const textareaId = id ?? generated; return <div className={cx('qh-field', error && 'is-invalid')}><label htmlFor={textareaId}>{label}</label><textarea id={textareaId} aria-invalid={error ? true : undefined} {...props}/>{description && <small>{description}</small>}{error && <small className="qh-field-error" role="alert">{error}</small>}</div>; }
export function Checkbox({label, description, ...props}: ComponentPropsWithoutRef<'input'> & {label: string; description?: string}) { const id = useId(); return <div className="qh-choice"><input {...props} id={props.id ?? id} type="checkbox"/><div><label htmlFor={props.id ?? id}>{label}</label>{description && <small>{description}</small>}</div></div>; }
export function Toggle({label, ...props}: ComponentPropsWithoutRef<'input'> & {label: string}) { const id = useId(); return <label className="qh-toggle"><input {...props} id={props.id ?? id} type="checkbox" role="switch"/><span aria-hidden="true"/><b>{label}</b></label>; }
export function SearchInput({value, onChange, placeholder = 'Search', shortcut, label = 'Search', ...props}: Omit<ComponentPropsWithoutRef<'input'>, 'type' | 'value' | 'onChange'> & {value?: string; onChange?: (value: string) => void; placeholder?: string; shortcut?: string; label?: string}) { const id = useId(); return <div className="qh-search"><label htmlFor={id} className="sr-only">{label}</label><Search size={15} aria-hidden="true"/><input {...props} id={id} type="search" value={value} onChange={event => onChange?.(event.target.value)} placeholder={placeholder}/>{shortcut && <kbd>{shortcut}</kbd>}</div>; }
export function FilterBar({children, onReset, resetLabel = 'Reset filters', action}: {children: ReactNode; onReset?: () => void; resetLabel?: string; action?: ReactNode}) { return <div className="qh-filter-bar"><div className="qh-filter-controls"><SlidersHorizontal size={15} aria-hidden="true"/>{children}</div><Cluster>{onReset && <button type="button" className="qh-action qh-action-quiet" onClick={onReset}><RotateCcw size={14} aria-hidden="true"/>{resetLabel}</button>}{action}</Cluster></div>; }
export function Toolbar({start, end, children, className = ''}: {start?: ReactNode; end?: ReactNode; children?: ReactNode; className?: string}) { return <div className={cx('qh-toolbar', className)}><div className="qh-toolbar-start">{start}{children}</div>{end && <div className="qh-toolbar-end">{end}</div>}</div>; }

export function Badge({children, tone = 'neutral', className = ''}: {children: ReactNode; tone?: Tone; className?: string}) { return <span className={cx('qh-badge', `qh-badge-${tone}`, className)}>{children}</span>; }
const statusTone: Record<StatusValue, Tone> = {ready: 'success', loading: 'info', running: 'info', queued: 'warning', completed: 'success', failed: 'error', partial: 'warning', cancelled: 'neutral', unavailable: 'warning', disconnected: 'error', unsupported: 'neutral', 'no-result': 'neutral'};
export function StatusBadge({status, label}: {status: StatusValue; label?: string}) { return <Badge tone={statusTone[status]}><span className="qh-status-dot" aria-hidden="true"/>{label ?? status.replace('-', ' ')}</Badge>; }
export function StatCard({label, value, detail, tone = 'neutral', loading = false, unavailable = false}: {label: string; value?: ReactNode; detail?: ReactNode; tone?: Tone; loading?: boolean; unavailable?: boolean}) { return <article className={cx('qh-stat-card', `qh-stat-${tone}`)} aria-busy={loading || undefined}><span>{label}</span>{loading ? <Skeleton variant="text"/> : unavailable ? <strong className="qh-stat-unavailable">Unavailable</strong> : <strong>{value ?? '—'}</strong>}{detail && <small>{detail}</small>}</article>; }

export type DataColumn<T> = {key: string; header: string; render?: (row: T) => ReactNode; numeric?: boolean; sortable?: boolean};
export function DataTable<T extends {id?: string | number}>({columns, rows, caption, getRowKey, sortKey, sortDirection, onSort, selectedRowKey, onRowClick, density = 'compact', loading = false, empty, error}: {columns: DataColumn<T>[]; rows?: T[]; caption: string; getRowKey?: (row: T, index: number) => string | number; sortKey?: string; sortDirection?: 'asc' | 'desc'; onSort?: (key: string) => void; selectedRowKey?: string | number; onRowClick?: (row: T) => void; density?: 'compact' | 'comfortable'; loading?: boolean; empty?: ReactNode; error?: ReactNode}) { const safeRows = rows ?? []; return <div className={cx('qh-table-wrap', `qh-table-${density}`)}>{error ? <div className="qh-table-state qh-table-error" role="alert">{error}</div> : loading ? <div className="qh-table-state" role="status"><Skeleton variant="rows" count={4}/></div> : safeRows.length === 0 ? <div className="qh-table-state">{empty ?? <EmptyState title="No records" description="There are no records to display."/>}</div> : <table><caption>{caption}</caption><thead><tr>{columns.map(column => <th key={column.key} scope="col" className={column.numeric ? 'is-numeric' : undefined}>{column.sortable && onSort ? <button type="button" className="qh-sort" onClick={() => onSort(column.key)} aria-label={`Sort by ${column.header}`}><span>{column.header}</span><ChevronsUpDown size={14} aria-hidden="true"/>{sortKey === column.key && <span className="sr-only">{sortDirection === 'desc' ? 'descending' : 'ascending'}</span>}</button> : column.header}</th>)}</tr></thead><tbody>{safeRows.map((row, index) => { const key = getRowKey?.(row, index) ?? row.id ?? index; return <tr key={String(key)} className={selectedRowKey === key ? 'is-selected' : undefined} onClick={() => onRowClick?.(row)} tabIndex={onRowClick ? 0 : undefined} onKeyDown={event => {if (onRowClick && (event.key === 'Enter' || event.key === ' ')) {event.preventDefault(); onRowClick(row);}}}>{columns.map(column => <td key={column.key} className={column.numeric ? 'is-numeric' : undefined}>{column.render ? column.render(row) : String((row as Record<string, unknown>)[column.key] ?? '—')}</td>)}</tr>;})}</tbody></table>}</div>; }

export function EmptyState({title, description, action}: {title: string; description?: ReactNode; action?: ReactNode}) { return <div className="qh-state"><strong>{title}</strong>{description && <span>{description}</span>}{action}</div>; }
export function LoadingState({label = 'Loading'}: {label?: string}) { return <div className="qh-state" role="status"><Skeleton variant="text"/><span>{label}</span></div>; }
export function ErrorState({title = 'Unable to load this view', description, action}: {title?: string; description?: ReactNode; action?: ReactNode}) { return <div className="qh-state qh-state-error" role="alert"><strong>{title}</strong>{description && <span>{description}</span>}{action}</div>; }
export function UnavailableState({title = 'Currently unavailable', description}: {title?: string; description?: ReactNode}) { return <div className="qh-state qh-state-warning" role="status"><strong>{title}</strong>{description && <span>{description}</span>}</div>; }
export function UnsupportedState({title = 'Not supported in this environment', description}: {title?: string; description?: ReactNode}) { return <div className="qh-state qh-state-neutral" role="status"><strong>{title}</strong>{description && <span>{description}</span>}</div>; }
export function ResultState({children}: {children: ReactNode}) { return <div className="qh-result-state" role="status">{children}</div>; }
export function Skeleton({variant = 'text', count = 1}: {variant?: 'text' | 'row' | 'rows' | 'card' | 'metric' | 'panel'; count?: number}) { return <div className={cx('qh-skeleton-group', `qh-skeleton-${variant}`)} aria-hidden="true">{Array.from({length: variant === 'rows' ? count : 1}, (_, index) => <span key={index}/>)}</div>; }
export function Pagination({page, pageCount, onChange, label = 'Pagination'}: {page: number; pageCount: number; onChange: (page: number) => void; label?: string}) { if (pageCount <= 1) return null; const pages = Array.from({length: pageCount}, (_, index) => index + 1); return <nav className="qh-pagination" aria-label={label}><button type="button" className="qh-action qh-action-quiet" onClick={() => onChange(page - 1)} disabled={page <= 1} aria-label="Previous page"><ChevronLeft size={15}/></button>{pages.map(item => <button type="button" key={item} className={cx('qh-page-number', item === page && 'is-current')} onClick={() => onChange(item)} aria-current={item === page ? 'page' : undefined}>{item}</button>)}<button type="button" className="qh-action qh-action-quiet" onClick={() => onChange(page + 1)} disabled={page >= pageCount} aria-label="Next page"><ChevronRight size={15}/></button></nav>; }
export function KeyValueList({items}: {items: Array<{label: string; value: ReactNode}>}) { return <dl className="qh-key-value-list">{items.map(item => <div key={item.label}><dt>{item.label}</dt><dd>{item.value}</dd></div>)}</dl>; }
export function MetadataRow({label, children}: {label: string; children: ReactNode}) { return <div className="qh-metadata-row"><dt>{label}</dt><dd>{children}</dd></div>; }
export function Notice({children, tone = 'info', title}: {children: ReactNode; tone?: 'info' | 'warning' | 'error' | 'research'; title?: string}) { return <aside className={cx('qh-notice', `qh-notice-${tone}`)} role={tone === 'error' ? 'alert' : 'note'}>{title && <strong>{title}</strong>}<span>{children}</span></aside>; }
export function SplitPane({main, aside, className = ''}: {main: ReactNode; aside: ReactNode; className?: string}) { return <div className={cx('qh-split-pane', className)}><div>{main}</div><aside>{aside}</aside></div>; }

export type ActionButtonProps = ComponentPropsWithoutRef<'button'> & {tone?: 'primary' | 'secondary' | 'quiet' | 'danger' | 'quantum'; size?: 'sm' | 'md' | 'lg'; loading?: boolean};
export function ActionButton({children, tone = 'primary', size = 'md', loading, disabled, className = '', ...props}: ActionButtonProps) { return <button {...props} className={cx('qh-action', `qh-action-${tone}`, `qh-action-${size}`, className)} disabled={disabled || loading} aria-busy={loading || undefined}>{loading && <span className="qh-button-spinner" aria-hidden="true"/>}{children}</button>; }
