import {ArrowRight, Atom, Check, CircuitBoard, FlaskConical, Gauge, Settings2} from 'lucide-react';
import type {ReactNode} from 'react';
import {Link} from 'react-router-dom';
import type {Circuit} from '../types';
import {environments, isNavigationItemActive, navigationItems} from '../navigation';
const quantumLab = environments.find(environment => environment.id === 'quantum-lab');
const studioRoute = navigationItems.find(item => item.label === 'Experiments')?.path ?? '/experiments';
const modelRoute = navigationItems.find(item => item.label === 'Training')?.path ?? '/training';
export function QuantumLabPage({currentPath, step, title, description, actions, children}: {currentPath: string; step: string; title: string; description: string; actions?: ReactNode; children: ReactNode}) {return <div className="quantum-lab-page"><header className="quantum-lab-header"><div><p className="quantum-lab-eyebrow"><Atom size={14} aria-hidden="true"/> QUANTUM LAB <span>/</span> {step}</p><h1>{title}</h1><p>{description}</p></div>{actions && <div className="quantum-lab-header-actions">{actions}</div>}</header><QuantumWorkflow currentPath={currentPath}/>{children}</div>}
export function QuantumWorkflow({currentPath}: {currentPath: string}) {return <nav className="quantum-workflow" aria-label="Quantum Lab workflow"><div className="quantum-workflow-label"><span>TECHNICAL WORKFLOW</span><small>Configuration, representation and evaluation are shown separately.</small></div><ol>{['Model','Encode','Circuit','Execute','Measure','Evaluate'].map((label, index) => <li key={label} className={index === 2 && isNavigationItemActive('/quantum', currentPath) ? 'active' : ''}><span className="quantum-workflow-index">{String(index + 1).padStart(2, '0')}</span><span>{label}</span>{index < 5 && <i aria-hidden="true">/</i>}</li>)}</ol><div className="quantum-workflow-links"><Link to={modelRoute}>Model Lab <ArrowRight size={13} aria-hidden="true"/></Link><Link to={studioRoute}>Research Studio <ArrowRight size={13} aria-hidden="true"/></Link></div></nav>}
export function QuantumPanel({title, description, actions, children, className = ''}: {title: string; description?: string; actions?: ReactNode; children: ReactNode; className?: string}) {return <section className={`quantum-panel ${className}`.trim()}><header className="quantum-panel-header"><div><h2>{title}</h2>{description && <p>{description}</p>}</div>{actions && <div>{actions}</div>}</header>{children}</section>}
export function QuantumNote({children, tone = 'neutral'}: {children: ReactNode; tone?: 'neutral' | 'warning' | 'research'}) {return <aside className={`quantum-note quantum-note-${tone}`}><CircuitBoard size={16} aria-hidden="true"/><div>{children}</div></aside>}
export function QuantumBackendState({available, runtimeVerified, execution}: {available?: boolean; runtimeVerified?: boolean; execution?: string}) {return <div className="quantum-backend-state"><span className={`quantum-state-dot ${available ? 'available' : 'unavailable'}`} aria-hidden="true"/><div><span>SIMULATOR / BACKEND</span><strong>{available === undefined ? 'Not checked' : available ? 'Available' : 'Unavailable'}</strong><small>{runtimeVerified ? 'Runtime verified' : execution || 'Local simulation capability only'}</small></div><b>{available ? <><Check size={13} aria-hidden="true"/> Configured</> : <><Gauge size={13} aria-hidden="true"/> Not configured</>}</b></div>}
export function QuantumCircuitContext({circuit}: {circuit?: Circuit}) {return <div className="quantum-circuit-context"><FlaskConical size={17} aria-hidden="true"/><div><span>CIRCUIT CONTEXT</span><strong>{circuit ? `${circuit.model_type.toUpperCase()} / ${circuit.backend}` : 'No representation generated'}</strong><small>{circuit ? `${circuit.qubits} qubits · logical depth ${circuit.logical_depth} · ${circuit.parameter_count} parameters` : 'Generate a structural circuit description to inspect it here.'}</small></div>{circuit && <b>Structural view</b>}</div>}
export function QuantumSettingsMark() {return <span className="quantum-settings-mark"><Settings2 size={17} aria-hidden="true"/></span>}
