import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {ArrowRight,Atom,BarChart3,Brain,FileText,GitBranch,ShieldAlert} from 'lucide-react';
import {Badge,Button,Card,Select} from './ui';
import {EmptyState,JsonDisclosure,MetricCard,Notice} from './Shared';
import {metric,modelLabels,seconds,shortId,isHybridModel} from '../utils/format';
import type {Circuit,Dataset,Experiment,ModelRecord,QuantumDiagnosticReport} from '../types/qhealth';
import type {QuantumVisualizationArtifact} from '../types/quantumVisualization';

type Props={mode:'live'|'verified';models:ModelRecord[];experiment?:Experiment;dataset?:Dataset;selectedModelId?:string;onModelChange?:(id:string)=>void;diagnostic?:QuantumDiagnosticReport|null;circuit?:Circuit|null;onLoadCircuit?:()=>void;loadingCircuit?:boolean;visualizationArtifacts?:QuantumVisualizationArtifact[];visualizationArtifactsLoading?:boolean};
const value=(input:unknown)=>input===null||input===undefined||input===''?'Not recorded':String(input);
const finite=(input:unknown):input is number=>typeof input==='number'&&Number.isFinite(input);
const record=(input:unknown):Record<string,unknown>|null=>input!==null&&typeof input==='object'&&!Array.isArray(input)?input as Record<string,unknown>:null;
function CircuitRows({circuit}:{circuit:Circuit}){return <div className="mt-4 space-y-2">{Array.from({length:circuit.qubits},(_,qubit)=><div className="flex items-center gap-3 rounded-lg border p-2" key={qubit}><strong className="mono w-12">q[{qubit}]</strong><div className="flex flex-wrap gap-2">{circuit.gates.filter(gate=>gate.qubits.includes(qubit)).map((gate,index)=><Badge tone="purple" key={`${gate.name}-${index}`}>{gate.name}{gate.parameters.length?` (${gate.parameters.join(', ')})`:''}</Badge>)}</div></div>)}</div>}

export function QuantumEvidenceLab({mode,models,experiment,dataset,selectedModelId,onModelChange,diagnostic,circuit,onLoadCircuit,loadingCircuit,visualizationArtifacts,visualizationArtifactsLoading}:Props){
 const quantumModels=models.filter(model=>['vqc','qsvc','qnn','hybrid_pennylane_torch'].includes(model.model_type));
 const [internal,setInternal]=useState(selectedModelId||quantumModels[0]?.id||'');
 useEffect(()=>{if(selectedModelId!==undefined)setInternal(selectedModelId)},[selectedModelId]);
 useEffect(()=>{if(!quantumModels.some(model=>model.id===internal))setInternal(quantumModels[0]?.id||'')},[models,internal]);
 const id=selectedModelId!==undefined?selectedModelId:internal;
 const model=quantumModels.find(item=>item.id===id)||quantumModels[0];
 const savedVisualizationEvidence=(visualizationArtifacts||[]).filter(artifact=>artifact.artifact_type==='quantum_visualization_evidence'&&artifact.model_id===model?.id);
 if(!model)return <EmptyState title="Quantum evidence not available">No quantum or hybrid model record exists in this experiment. Capability availability is not presented as executed evidence.</EmptyState>;
 const q=(model.details.quantum||{}) as Record<string,unknown>;
 const config=(isHybridModel(model.model_type)?experiment?.config.hybrid:experiment?.config.quantum) as unknown as Record<string,unknown>|undefined;
 const persistedCircuit=((q.circuit&&typeof q.circuit==='object')?q.circuit:null) as Circuit|null;
 const shownCircuit=circuit||persistedCircuit;
 const framework=value(q.framework||(isHybridModel(model.model_type)?'PennyLane + PyTorch':'Qiskit'));
 const provider=value(q.provider_display_name||q.provider_id||config?.provider_id);
 const backend=value(q.backend||q.backend_id||config?.backend||diagnostic?.execution_profile.backend);
 const execution=value(q.execution_kind||q.execution_mode||config?.execution_mode||diagnostic?.execution_profile.execution_mode);
 const realHardware=q.real_hardware===true||diagnostic?.execution_profile.real_hardware===true;
 const qubits=q.qubits??config?.qubits??diagnostic?.resource_profile.qubits_observed;
 const shots=config?.shots??diagnostic?.resource_profile.shots_configured;
 const timing=model.metrics.timing;
 const diagnosticStatus=diagnostic?.status||'not recorded';
 const findings=[`${modelLabels[model.model_type]} used ${execution} on ${backend}.`,finite(qubits)?`${qubits} logical qubits were recorded for this experiment.`:null,finite(shots)?`${shots} shots were configured for the recorded execution.`:'Shots were not recorded or not applicable to the exact-expectation backend.',finite(timing?.final_training_seconds)?`Observed final training time was ${seconds(timing.final_training_seconds)} on this execution environment.`:null].filter(Boolean);
 return <div className="space-y-5">
  <Card title="Quantum execution summary" description="Persisted quantum and hybrid execution evidence; provider capability is kept separate from execution actually performed."><label className="field max-w-xl"><span>Quantum / hybrid model</span><Select aria-label="Quantum evidence model" value={model.id} onChange={event=>{setInternal(event.target.value);onModelChange?.(event.target.value)}}>{quantumModels.map(item=><option key={item.id} value={item.id}>{modelLabels[item.model_type]} · {shortId(item.id)}</option>)}</Select></label><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><MetricCard label="MODEL" value={modelLabels[model.model_type]} detail={isHybridModel(model.model_type)?'Hybrid':'Quantum'}/><MetricCard label="FRAMEWORK" value={framework} detail={provider}/><MetricCard label="EXECUTION MODE" value={execution} detail={backend}/><MetricCard label="REAL HARDWARE" value={realHardware?'USED':'NOT USED'} detail={realHardware?'Explicitly recorded':'Local/simulator boundary'}/><MetricCard label="LOGICAL QUBITS" value={value(qubits)} detail="Not physical hardware count"/><MetricCard label="SHOTS" value={value(shots)} detail={shots===null||shots===undefined?'Not recorded / not applicable':'Configured measurement shots'}/><MetricCard label="DIAGNOSTICS" value={diagnosticStatus.toUpperCase()} detail={diagnostic?'Persisted report':'No report loaded'}/><MetricCard label="EVIDENCE SOURCE" value={mode==='verified'?'VERIFIED / PRECOMPUTED':'PERSISTED MODEL'} detail="No execution on page load"/></div></Card>
  <Notice tone="amber"><strong>{realHardware?'Hardware execution is explicitly recorded.':'Local simulation boundary — real hardware was not used.'}</strong> Simulator timing does not predict QPU wall-clock runtime, cost, energy use, scalability, or quantum advantage.</Notice>
  <div className="grid gap-5 lg:grid-cols-2"><Card title="Quantum resources" description="Logical resources and model configuration actually recorded for the selected artifact."><div className="grid gap-3 sm:grid-cols-2"><MetricCard label="QUBITS" value={value(qubits)}/><MetricCard label="FEATURE MAP REPS" value={value(config?.feature_map_reps)}/><MetricCard label="ANSATZ REPS / LAYERS" value={value(config?.ansatz_reps??config?.quantum_layers)}/><MetricCard label="ENTANGLEMENT" value={value(config?.entanglement)}/><MetricCard label="PARAMETERS" value={value(q.quantum_parameter_count??diagnostic?.resource_profile.parameter_count)}/><MetricCard label="CIRCUIT DEPTH" value={value(shownCircuit?.logical_depth??diagnostic?.resource_profile.circuit_depth)}/></div></Card><Card title="Optimization and hybrid classical component" description="Only fields supported by the selected model configuration are shown."><div className="grid gap-3 sm:grid-cols-2"><MetricCard label="OPTIMIZER" value={value(q.optimizer||config?.optimizer||diagnostic?.optimizer_profile.optimizer)}/><MetricCard label="MAX ITERATIONS / EPOCHS" value={value(config?.maxiter??config?.epochs??diagnostic?.optimizer_profile.iterations)}/><MetricCard label="LEARNING RATE" value={value(config?.learning_rate)}/><MetricCard label="BATCH SIZE" value={value(config?.batch_size)}/><MetricCard label="CLASSICAL HIDDEN DIMS" value={Array.isArray(config?.classical_hidden_dimensions)?config?.classical_hidden_dimensions.join(' × '):value((q.configuration as Record<string,unknown>|undefined)?.hidden_dimensions)}/><MetricCard label="CLASSICAL PARAMETERS" value={value(q.classical_parameter_count)}/></div></Card></div>
  <Card title="Observed execution measurements" description="Observed runtime on this execution environment — not a general infrastructure or QPU benchmark."><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><MetricCard label="FINAL TRAINING" value={seconds(timing?.final_training_seconds)}/><MetricCard label="TOTAL CV" value={seconds(timing?.cv_total_seconds)}/><MetricCard label="MEAN CV FOLD" value={timing?.cv_fold_seconds?.length?seconds(timing.cv_fold_seconds.reduce((sum,item)=>sum+item,0)/timing.cv_fold_seconds.length):'Not recorded'}/><MetricCard label="HELD-OUT INFERENCE" value={seconds(timing?.test_inference_seconds)}/><MetricCard label="INFERENCE / SAMPLE" value={seconds(timing?.test_inference_seconds_per_sample)}/></div></Card>
  <Card title="Quantum circuit evidence" description="Backend-described fitted circuit only; no circuit is reconstructed from incomplete metadata.">{shownCircuit?<><div className="grid gap-3 sm:grid-cols-3"><MetricCard label="QUBITS" value={shownCircuit.qubits}/><MetricCard label="LOGICAL DEPTH" value={value(shownCircuit.logical_depth)}/><MetricCard label="PARAMETERS" value={shownCircuit.parameter_count}/></div><CircuitRows circuit={shownCircuit}/><JsonDisclosure label="Gate counts and circuit limitations" value={{gate_counts:shownCircuit.gate_counts,limitation:shownCircuit.limitation}}/></>:<><Notice tone="amber">Circuit evidence not available for this artifact.</Notice>{mode==='live'&&onLoadCircuit&&<Button className="mt-3" variant="outline" disabled={loadingCircuit} onClick={onLoadCircuit}>{loadingCircuit?'Retrieving persisted circuit…':'Retrieve fitted circuit evidence'}</Button>}</>}</Card>
  <Card title="Persisted quantum diagnostics" description="Diagnostic fields are read from an existing report; no diagnostic computation is triggered by viewing this page.">{diagnostic?<><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><MetricCard label="STATUS" value={diagnostic.status.toUpperCase()}/><MetricCard label="ENCODED FEATURES" value={value(diagnostic.feature_encoding.encoded_features)}/><MetricCard label="PARAMETERIZED GATES" value={value(diagnostic.circuit_structure.parameterized_gates)}/><MetricCard label="NOISE" value={diagnostic.noise_profile.noise_enabled?'Enabled':value(diagnostic.noise_profile.noise_model)}/></div>{diagnostic.warnings.length>0&&<div className="mt-4 space-y-2">{diagnostic.warnings.map(item=><Notice tone={item.severity==='BLOCKER'?'amber':'blue'} key={item.code}><strong>{item.title}:</strong> {item.description}</Notice>)}</div>}<JsonDisclosure label="Complete persisted diagnostic context" value={diagnostic}/></>:<Notice tone="amber">Quantum diagnostic evidence is not recorded for this model. Capability availability does not mean diagnostics were executed.</Notice>}</Card>
  {mode==='live'&&(visualizationArtifactsLoading||savedVisualizationEvidence.length>0)&&<Card title="Saved Quantum Lab simulation evidence" description="These backend-generated snapshots are linked to the existing experiment artifact registry and report. They are not fitted-model predictions.">
   {visualizationArtifactsLoading?<Notice>Loading saved visualization evidence…</Notice>:<div className="space-y-3">{savedVisualizationEvidence.map(artifact=>{
    const details=artifact.details||{};
    const contract=record(details.contract);
    const state=record(contract?.state);
    const provider=record(contract?.provider);
    return <div className="rounded-lg border p-3" key={artifact.id}>
     <div className="flex flex-wrap items-center justify-between gap-2"><strong className="text-xs">{artifact.name}</strong><Badge tone="green">{value(state?.status||contract?.status)}</Badge></div>
     <div className="mt-2 grid gap-2 text-xs sm:grid-cols-2">
      <span><span className="muted">Artifact ID</span><br/><strong className="mono break-all">{artifact.id}</strong></span>
      <span><span className="muted">Simulator / backend</span><br/><strong>{value(state?.execution_source)} · {value(state?.simulator||provider?.backend_id)}</strong></span>
      <span><span className="muted">Run</span><br/><strong className="mono break-all">{value(artifact.run_id)}</strong></span>
      <span><span className="muted">Request fingerprint</span><br/><strong className="mono break-all">{value(details.request_fingerprint)}</strong></span>
     </div>
     <Link className="mt-3 inline-flex items-center gap-1 text-xs text-primary" to={`/experiments/${model.experiment_id}`}>Open linked experiment report <ArrowRight size={13}/></Link>
    </div>;
   })}</div>}
  </Card>}
  <Card title="Classical vs quantum context" description="Observed results under this experiment; no quantum advantage, speedup, or superiority claim."><div className="table-wrap overflow-x-auto"><table className="data-table min-w-[900px]"><thead><tr><th>Model</th><th>Family</th><th>Held-out ROC-AUC</th><th>CV ROC-AUC</th><th>Training runtime</th><th>Logical qubits</th><th>Execution</th></tr></thead><tbody>{models.filter(item=>item.experiment_id===model.experiment_id).map(item=>{const itemQ=(item.details.quantum||{}) as Record<string,unknown>;const family=['vqc','qsvc','qnn'].includes(item.model_type)?'Quantum':isHybridModel(item.model_type)?'Hybrid':'Classical';return <tr key={item.id}><td><strong>{modelLabels[item.model_type]}</strong></td><td>{family}</td><td>{metric(item.metrics.test?.roc_auc)}</td><td>{metric(item.metrics.validation?.summary.roc_auc?.mean)}</td><td>{seconds(item.metrics.timing?.final_training_seconds)}</td><td>{family==='Classical'?'Not applicable':value(itemQ.qubits)}</td><td>{family==='Classical'?'Classical execution':value(itemQ.execution_kind||itemQ.execution_mode)}</td></tr>})}</tbody></table></div></Card>
  <Card title="Machine-derived quantum findings" description="Descriptive statements from visible persisted evidence only."><ul className="space-y-2 text-sm">{findings.map(item=><li key={String(item)}>• {item}</li>)}</ul></Card>
  <div className="grid gap-5 lg:grid-cols-2"><Card title="Evidence context"><div className="space-y-2 text-xs">{[['Experiment ID',experiment?.id||model.experiment_id],['Dataset',dataset?.name||model.dataset_id],['Dataset hash',dataset?.sha256],['Model ID',model.id],['Artifact ID',model.details.model_artifact_id||model.details.artifact_id],['Protocol fingerprint',experiment?.protocol_fingerprint],['Configuration fingerprint',diagnostic?.configuration_fingerprint],['Timestamp',diagnostic?.created_at||model.created_at]].map(([label,item])=><div className="flex justify-between gap-3 border-b py-2" key={String(label)}><span className="muted">{String(label)}</span><strong className="mono break-all text-right">{value(item)}</strong></div>)}</div></Card><Card title="Quantum evidence limitations"><ul className="space-y-2 text-xs muted">{(diagnostic?.limitations||[]).map(item=><li key={item}>• {item}</li>)}<li>• Provider capability does not establish that hardware execution occurred.</li><li>• Logical resources are not equivalent to physical-device performance.</li><li>• Simulator measurements do not support a quantum-advantage or hardware-speedup claim.</li><li>• Results are limited to the evaluated biomedical tabular experiment.</li></ul></Card></div>
  <Card title="Continue the research investigation"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['/comparison','Research Results Center',BarChart3],['/comparison','Diagnostic Evidence',Brain],['/robustness','Robustness',ShieldAlert],['/explainability','Explainability',Brain],['/prediction','Prediction',ArrowRight],['/experiments/'+model.experiment_id,'Evidence Package',FileText],['/experiments/'+model.experiment_id,'Experiment Lineage',GitBranch],['/quantum','Quantum Evidence',Atom]].map(([path,label,Icon])=><Link className="flex items-center gap-3 rounded-xl border p-4 hover:bg-primary/5" to={String(path)} key={String(label)}><Icon size={15} className="text-primary"/><strong className="text-xs">{String(label)}</strong></Link>)}</div></Card>
 </div>;
}
