import {Archive, ArrowRight, Beaker, FileText, FlaskConical, Search, Sparkles} from 'lucide-react';
import type {ReactNode} from 'react';
import {Link} from 'react-router-dom';
import {navigationItems} from '../navigation';
const modelRoute = navigationItems.find(item => item.label === 'Training')?.path ?? '/training';
const quantumRoute = navigationItems.find(item => item.label === 'Quantum circuit')?.path ?? '/quantum';
export function ResearchStudioPage({step, title, description, actions, children}: {step: string; title: string; description: string; actions?: ReactNode; children: ReactNode}) {return <div className="studio-page"><header className="studio-header"><div><p className="studio-eyebrow"><FlaskConical size={14} aria-hidden="true"/> RESEARCH STUDIO <span>/</span> {step}</p><h1>{title}</h1><p>{description}</p></div>{actions && <div className="studio-header-actions">{actions}</div>}</header><StudioWorkflow/>{children}</div>}
export function StudioWorkflow() {return <nav className="studio-workflow" aria-label="Research Studio workflow"><div><span>RESEARCH RECORD</span><small>Organize evidence without turning metadata into a scientific result.</small></div><Link to="/experiments" className="active"><Archive size={15} aria-hidden="true"/> Registry</Link><span aria-hidden="true">/</span><Link to={modelRoute}><Beaker size={15} aria-hidden="true"/> Model Lab</Link><span aria-hidden="true">/</span><Link to={quantumRoute}><Sparkles size={15} aria-hidden="true"/> Quantum Lab</Link></nav>}
export function StudioPanel({title, description, actions, children, className = ''}: {title: string; description?: string; actions?: ReactNode; children: ReactNode; className?: string}) {return <section className={`studio-panel ${className}`.trim()}><header className="studio-panel-header"><div><h2>{title}</h2>{description && <p>{description}</p>}</div>{actions && <div>{actions}</div>}</header>{children}</section>}
export function StudioSearch({value, onChange}: {value: string; onChange: (value: string) => void}) {return <label className="studio-search"><Search size={16} aria-hidden="true"/><span className="sr-only">Search experiments</span><input aria-label="Search experiments" placeholder="Search experiment IDs, datasets or statuses" value={value} onChange={e => onChange(e.target.value)}/></label>}
export function StudioUnavailable({title, children}: {title: string; children: ReactNode}) {return <div className="studio-unavailable"><FileText size={18} aria-hidden="true"/><div><strong>{title}</strong><p>{children}</p></div></div>}
export function StudioNextLinks() {return <div className="studio-next-links"><Link to={modelRoute}>Open Model Lab <ArrowRight size={14} aria-hidden="true"/></Link><Link to={quantumRoute}>Open Quantum Lab <ArrowRight size={14} aria-hidden="true"/></Link></div>}
