import {useEffect,useMemo,useState} from 'react';
import {Link} from 'react-router-dom';
import {ArrowRight,Atom,BarChart3,Brain,FileText,GitBranch,ShieldAlert} from 'lucide-react';
import {Badge,Button,Card,Select} from './ui';
import {EmptyState,JsonDisclosure,MetricCard,Notice,StatusBadge} from './Shared';
import {ProbabilityBand} from './TremorWorkbench';
import {InfluenceBars} from './Charts';
import {metric,modelLabels,shortId,isHybridModel,isQiskitQuantumModel} from '../utils/format';
import type {Dataset,Experiment,MetricName,ModelInputSchema,ModelRecord,Prediction,VerifiedPredictionCase} from '../types/qhealth';

export interface CrossModelPrediction {model:ModelRecord;prediction?:Prediction;reason?:string}
type Props={
 mode:'live'|'verified';model?:ModelRecord;models:ModelRecord[];experiment?:Experiment;dataset?:Dataset;schema?:ModelInputSchema;
 input?:Record<string,string|number|boolean|null>;prediction?:Prediction;verifiedCases?:VerifiedPredictionCase[];
 crossResults?:CrossModelPrediction[];sameInputVerified?:boolean;onCompare?:()=>void;comparing?:boolean;
};
type Family='Classical'|'Quantum'|'Hybrid';

const rankingOrder:MetricName[]=['roc_auc','f1','accuracy','recall','sensitivity','specificity','precision'];
function finite(value:unknown):value is number{return typeof value==='number'&&Number.isFinite(value)}
function family(model:ModelRecord):Family{if(isHybridModel(model.model_type))return 'Hybrid';if(isQiskitQuantumModel(model.model_type))return 'Quantum';return 'Classical'}
function tone(value:Family):'blue'|'purple'|'amber'{return value==='Classical'?'blue':value==='Quantum'?'purple':'amber'}
function valueText(value:unknown){return value===null||value===undefined||value===''?'Not recorded':String(value)}
function classCounts(rows:CrossModelPrediction[]){return rows.flatMap(row=>row.prediction?.predictions?.[0]?.predicted_class?[row.prediction.predictions[0].predicted_class]:[]).reduce<Record<string,number>>((acc,value)=>{acc[value]=(acc[value]||0)+1;return acc},{})}
function familySummary(rows:CrossModelPrediction[],kind:Family){
 const valid=rows.filter(row=>family(row.model)===kind&&row.prediction?.predictions?.[0]);
 const counts=classCounts(valid);const labels=Object.keys(counts);
 return {total:valid.length,label:labels.length===1?labels[0]:labels.length>1?'Mixed':'Not available',counts};
}
function LocalContributionList({title,items}:{title:string;items:NonNullable<Prediction['explanation']>['contributions']}){
 return <div><h4 className="text-xs font-semibold uppercase tracking-wide">{title}</h4><div className="mt-2 space-y-2">{items.length?items.map(item=><div className="rounded-lg border p-3" key={item.feature}><div className="flex items-center justify-between gap-3"><div><strong className="text-sm">{item.feature}</strong><small className="block muted">Original value: {valueText(item.original_value)}</small></div><strong className={item.direction==='toward_positive'?'text-red-600':'text-blue-600'}>{item.contribution===undefined?'Not recorded':`${item.contribution>=0?'+':''}${item.contribution.toFixed(4)}`}</strong></div><p className="mt-1 text-xs muted">{item.interpretation}</p></div>):<p className="text-xs muted">No persisted contribution in this direction.</p>}</div></div>;
}
function bestObserved(models:ModelRecord[]){
 const criterion=rankingOrder.find(name=>models.some(model=>finite(model.metrics.test?.[name])));
 if(!criterion)return undefined;
 return models.filter(model=>finite(model.metrics.test?.[criterion])).sort((a,b)=>(b.metrics.test?.[criterion] as number)-(a.metrics.test?.[criterion] as number)||modelLabels[a.model_type].localeCompare(modelLabels[b.model_type]))[0]&&{model:models.filter(model=>finite(model.metrics.test?.[criterion])).sort((a,b)=>(b.metrics.test?.[criterion] as number)-(a.metrics.test?.[criterion] as number)||modelLabels[a.model_type].localeCompare(modelLabels[b.model_type]))[0],criterion};
}

export function ResearchPredictionLab({mode,model,models,experiment,dataset,schema,input,prediction,verifiedCases=[],crossResults=[],sameInputVerified=false,onCompare,comparing=false}:Props){
 const [caseId,setCaseId]=useState(verifiedCases[0]?.case_id||'');
 useEffect(()=>{if(!verifiedCases.some(item=>item.case_id===caseId))setCaseId(verifiedCases[0]?.case_id||'')},[verifiedCases,caseId]);
 const verifiedCase=verifiedCases.find(item=>item.case_id===caseId)||verifiedCases[0];
 const liveItem=prediction?.predictions?.[0];
 const output=verifiedCase?{predictedClass:verifiedCase.predicted_class,probability:verifiedCase.probability_positive,decisionScore:null as number|null,riskCategory:verifiedCase.case_label,threshold:verifiedCase.threshold,thresholdSource:verifiedCase.threshold_source,sample:verifiedCase.case_id}:liveItem?{predictedClass:liveItem.predicted_class,probability:liveItem.probability_positive,decisionScore:liveItem.decision_score,riskCategory:liveItem.research_risk_category,threshold:prediction!.operating_threshold,thresholdSource:prediction!.threshold_source,sample:liveItem.sample}:undefined;
 const activeInput=verifiedCase?.input||input;
 const currentModel=verifiedCase?models.find(item=>item.id===verifiedCase.model_id)||model:model;
 const relatedModels=models.filter(item=>!currentModel||item.experiment_id===currentModel.experiment_id);
 const best=bestObserved(relatedModels);
 const operating=currentModel?.metrics.operating_point;
 const execution=(currentModel?.details.quantum||{}) as Record<string,unknown>;
 const comparable=crossResults.filter(row=>row.prediction?.predictions?.[0]);
 const unavailable=crossResults.filter(row=>!row.prediction);
 const agreement=classCounts(comparable);const agreementEntries=Object.entries(agreement).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]));
 const disagreement=agreementEntries.length>1;
 const families:Family[]=['Classical','Quantum','Hybrid'];
 const interpretation=output&&finite(output.probability)&&finite(output.threshold)?`The model returned the ${output.predictedClass} class with a positive-class model probability ${output.probability>=output.threshold?'at or above':'below'} the persisted research threshold.`:output&&finite(output.decisionScore)&&finite(output.threshold)?`The model returned the ${output.predictedClass} class from the backend decision score relative to the persisted research threshold.`:output?`The backend returned the ${output.predictedClass} class; a probability or decision-score comparison is not available.`:'';
 const contextDetails=(currentModel?.details||{}) as Record<string,unknown>;

 if(!currentModel||!output)return <EmptyState title="No research prediction available">Select a trained model, provide the exact model input, and deliberately request a prediction. No output is generated automatically.</EmptyState>;
 return <div className="space-y-5">
  <Card title="Prediction overview" description={`${mode==='verified'?'Verified / precomputed representative case':'Live model prediction response'} with traceable model and experiment context.`}>
   {mode==='verified'&&verifiedCases.length>1&&<label className="field mb-4 max-w-xl"><span>Representative research case</span><Select aria-label="Representative research case" value={verifiedCase?.case_id||''} onChange={event=>setCaseId(event.target.value)}>{verifiedCases.map(item=><option key={item.case_id} value={item.case_id}>{item.case_id} · {item.case_label.replaceAll('_',' ')}</option>)}</Select></label>}
   <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><MetricCard label="MODEL" value={modelLabels[currentModel.model_type]} detail={`${family(currentModel)} · ${shortId(currentModel.id)}`}/><MetricCard label="EXPERIMENT" value={shortId(currentModel.experiment_id)} detail={experiment?.status||'Status not recorded'}/><MetricCard label="DATASET" value={dataset?.name||shortId(currentModel.dataset_id)} detail={dataset?.sha256?`SHA-256 ${dataset.sha256}`:'Hash not recorded'}/><MetricCard label="PREDICTION STATUS" value="Completed" detail={mode==='verified'?'Packaged evidence':'Live API response'}/><MetricCard label="OUTPUT" value={output.predictedClass} detail="Predicted class"/><MetricCard label="SOURCE" value={mode==='verified'?'Verified / precomputed':'Live model prediction'} detail={output.sample}/><MetricCard label="EXECUTION" value={valueText(execution.execution_kind||'Classical / not separately recorded')} detail={execution.real_hardware?'Hardware reported':'No hardware claim'}/><MetricCard label="TIMESTAMP" value="Not recorded" detail="Prediction response has no persisted timestamp"/></div>
  </Card>

  <Notice tone="amber"><strong>Research use only — not a clinical diagnosis.</strong> This is a research model output under the evaluated configuration, not a medical risk score, screening decision, treatment recommendation, or prognosis.</Notice>

  <div className="tremor-grid-main">
   <Card title="Research input" description="Original submitted or packaged feature values. Model-internal transformed values are not shown.">{activeInput?<div className="table-wrap overflow-x-auto"><table className="data-table"><thead><tr><th>Feature</th><th>Original research input</th></tr></thead><tbody>{Object.entries(activeInput).map(([key,value])=><tr key={key}><td><strong>{key}</strong></td><td>{valueText(value)}</td></tr>)}</tbody></table></div>:<Notice tone="amber">The submitted input context was not recorded.</Notice>}</Card>
   <Card title="Model input schema" description="Exact backend-provided input contract for the selected model.">{schema?<><div className="grid gap-3 sm:grid-cols-2"><MetricCard label="POSITIVE LABEL" value={schema.positive_label}/><MetricCard label="NEGATIVE LABEL" value={schema.negative_label}/></div><div className="table-wrap mt-4 overflow-x-auto"><table className="data-table"><thead><tr><th>Feature</th><th>Expected type</th><th>Nullable</th></tr></thead><tbody>{schema.features.map(field=><tr key={field.name}><td>{field.name}</td><td>{field.type}</td><td>{field.nullable?'Yes':'No'}</td></tr>)}</tbody></table></div><p className="mt-3 text-xs muted">Missing-value strategy: {schema.missing_strategy||'Not recorded'}.</p></>:<Notice tone="amber">The verified package does not include a model input-schema record. No schema is inferred from the example values.</Notice>}</Card>
  </div>

  <Card title="Research model output" description={prediction?.probability_status||'Representative packaged model output.'}>
   <div className="rounded-xl border bg-primary/5 p-5"><div className="metric-label">PREDICTED CLASS</div><div className="mt-2 flex flex-wrap items-center gap-3"><h2 className="text-3xl font-semibold">{output.predictedClass}</h2><Badge tone="blue">{family(currentModel)}</Badge></div>{finite(output.probability)&&<div className="mt-5"><ProbabilityBand probability={output.probability} threshold={output.threshold} label="Positive-class model probability"/></div>}<div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><MetricCard label="MODEL PROBABILITY" value={finite(output.probability)?metric(output.probability):'Probability not available for this model'}/><MetricCard label="DECISION SCORE" value={finite(output.decisionScore)?output.decisionScore.toFixed(4):'Decision score not recorded'}/><MetricCard label="RESEARCH THRESHOLD" value={finite(output.threshold)?output.threshold.toFixed(4):'Not recorded'}/><MetricCard label="THRESHOLD SOURCE" value={output.thresholdSource?.replaceAll('_',' ')||'Not recorded'}/><MetricCard label="RESEARCH CATEGORY" value={output.riskCategory?.replaceAll('_',' ')||'Not assigned'}/></div></div>
   {interpretation&&<div className="mt-4"><Notice tone="blue">{interpretation} This statement describes model behavior only.</Notice></div>}
  </Card>

  <div className="tremor-grid-main">
   <Card title="Research operating point" description="Persisted threshold context; selection is not recalculated on this page."><div className="grid gap-3 sm:grid-cols-2"><MetricCard label="THRESHOLD" value={finite(output.threshold)?output.threshold.toFixed(4):'Not recorded'}/><MetricCard label="STRATEGY" value={operating?.selection_strategy?.replaceAll('_',' ')||experiment?.config?.threshold_strategy?.replaceAll('_',' ')||'Not recorded'}/><MetricCard label="SOURCE" value={output.thresholdSource?.replaceAll('_',' ')||operating?.threshold_source||'Not recorded'}/><MetricCard label="TARGET SENSITIVITY" value={metric(operating?.target_sensitivity)}/><MetricCard label="VALIDATION SENSITIVITY" value={metric(operating?.validation_metrics?.sensitivity)}/><MetricCard label="VALIDATION SPECIFICITY" value={metric(operating?.validation_metrics?.specificity)}/></div><p className="mt-3 text-xs muted">Research operating point only — never a clinical cutoff.</p></Card>
   <Card title="Selected model vs best observed model" description="The selected prediction model is never silently replaced by the Results Center leader."><div className="space-y-4"><div className="rounded-lg border p-4"><div className="metric-label">SELECTED MODEL</div><strong className="mt-1 block text-lg">{modelLabels[currentModel.model_type]}</strong><span className="text-xs muted">This model produced the displayed prediction.</span></div><div className="rounded-lg border p-4"><div className="metric-label">BEST OBSERVED MODEL IN THIS EXPERIMENT</div>{best?<><strong className="mt-1 block text-lg">{modelLabels[best.model.model_type]}</strong><span className="text-xs muted">Held-out {best.criterion==='roc_auc'?'ROC-AUC':best.criterion.replaceAll('_',' ')} · {metric(best.model.metrics.test?.[best.criterion])}</span></>:<span className="mt-1 block text-sm muted">No supported persisted ranking metric.</span>}</div></div></Card>
  </div>

  <Card title="Cross-model prediction" description="Explicitly evaluate the same submitted research input only on ready models with a verified compatible schema.">
   {mode==='live'&&onCompare&&<Button disabled={comparing||!activeInput} onClick={onCompare}><BarChart3 size={14}/>{comparing?'Evaluating compatible models…':'Compare compatible models on this input'}</Button>}
   {mode==='verified'&&<Notice tone="blue">The verified package contains representative outputs for one model only. Cross-model comparison is not fabricated.</Notice>}
   {crossResults.length>0&&<><div className="mt-4 flex flex-wrap items-center gap-2"><Badge tone={sameInputVerified?'green':'amber'}>{sameInputVerified?'SAME INPUT VERIFIED':'INPUT COMPARABILITY NOT VERIFIED'}</Badge><span className="text-xs muted">{sameInputVerified?'The exact current row was submitted in one explicit comparison action to each schema-compatible model.':'No shared-input claim is made.'}</span></div><div className="table-wrap mt-4 overflow-x-auto"><table className="data-table"><thead><tr><th>Model</th><th>Family</th><th>Prediction</th><th>Probability</th><th>Decision score</th><th>Threshold</th><th>Status</th></tr></thead><tbody>{crossResults.map(row=>{const item=row.prediction?.predictions?.[0];return <tr key={row.model.id}><td><strong>{modelLabels[row.model.model_type]}</strong></td><td><Badge tone={tone(family(row.model))}>{family(row.model)}</Badge></td><td>{item?.predicted_class||'Not available'}</td><td>{finite(item?.probability_positive)?metric(item?.probability_positive):'Not available'}</td><td>{finite(item?.decision_score)?item?.decision_score?.toFixed(4):'Not available'}</td><td>{finite(row.prediction?.operating_threshold)?row.prediction?.operating_threshold.toFixed(4):'Not available'}</td><td>{row.prediction?'Evaluated':row.reason||'Not evaluated'}</td></tr>})}</tbody></table></div></>}
  </Card>

  {comparable.length>0&&<div className="tremor-grid-main"><Card title="Observed model agreement" description="Descriptive agreement on this displayed research input; agreement is not truth or clinical evidence."><div className="grid gap-3 sm:grid-cols-2">{agreementEntries.map(([label,count])=><MetricCard key={label} label={label.toUpperCase()} value={`${count} / ${comparable.length} models`}/>)}</div>{disagreement?<div className="mt-4"><Notice tone="amber"><strong>Model disagreement detected.</strong> Observed disagreement across evaluated models is retained rather than resolved automatically.</Notice></div>:<div className="mt-4"><Notice tone="green">All displayed compatible models returned the same class for this research input. This does not establish correctness.</Notice></div>}</Card><Card title="Model family summary" description="Descriptive family-level outputs; no superiority or quantum-advantage claim."><div className="grid gap-3">{families.map(kind=>{const summary=familySummary(comparable,kind);return <div className="rounded-lg border p-3" key={kind}><div className="flex items-center justify-between"><Badge tone={tone(kind)}>{kind.toUpperCase()}</Badge><span className="text-xs muted">{summary.total} evaluated</span></div><strong className="mt-2 block">{summary.label}</strong><span className="text-[10px] muted">{Object.entries(summary.counts).map(([name,count])=>`${count} ${name}`).join(' · ')||'No compatible result'}</span></div>})}</div></Card></div>}
  {unavailable.length>0&&<Notice tone="amber"><strong>Not compared:</strong> {unavailable.map(row=>`${modelLabels[row.model.model_type]} — ${row.reason||'output unavailable'}`).join('; ')}.</Notice>}

  <div className="tremor-grid-main">
   <Card title="Prediction evidence context" description="Compact traceability without filesystem paths or infrastructure details."><div className="grid gap-2 text-xs">{[
    ['Experiment ID',experiment?.id||currentModel.experiment_id],['Model ID',currentModel.id],['Dataset ID',dataset?.id||currentModel.dataset_id],['Dataset hash',dataset?.sha256],['Model artifact ID',contextDetails.model_artifact_id||contextDetails.artifact_id],['Prediction context ID',verifiedCase?.case_id],['Model type',currentModel.model_type],['Threshold',finite(output.threshold)?output.threshold.toString():undefined],['Timestamp',undefined],['Execution mode',execution.execution_kind]
   ].map(([key,value])=><div className="flex flex-wrap justify-between gap-3 border-b py-2 last:border-0" key={String(key)}><span className="muted">{String(key)}</span><strong className="mono break-all text-right">{value?String(value):'Not recorded'}</strong></div>)}</div><JsonDisclosure label="Prediction limitations and decision context" value={{decision_rule:prediction?.decision_rule,probability_status:prediction?.probability_status,threshold_source:output.thresholdSource,limitations:prediction?.limitations||['Representative packaged evidence; no live request was executed.']}}/></Card>
   <Card title="Explanation connection" description="Continue into the existing Explainability Research Lab for model-derived contribution evidence."><div className="flex items-center gap-3"><Brain className="text-primary" size={22}/><div><strong>{prediction?.explanation?'Local explanation returned with this output':'Explanation capability available through the existing workflow'}</strong><p className="text-xs muted">No explanation is generated automatically from this link.</p></div></div>{prediction?.explanation&&<div className="mt-5"><div className="flex flex-wrap items-center gap-2"><Badge tone="purple">{prediction.explanation.model_display_name}</Badge><Badge tone="blue">{prediction.explanation.method_display}</Badge></div><h3 className="mt-3 text-lg font-semibold">Post-hoc model explanation</h3><p className="text-xs muted">Contribution to the returned research model output; not medical causation.</p><div className="mt-4 grid gap-3 sm:grid-cols-3"><MetricCard label="MODEL PROBABILITY" value={metric(prediction.explanation.prediction_context.probability_positive)}/><MetricCard label="RESEARCH THRESHOLD" value={prediction.explanation.prediction_context.operating_threshold.toFixed(4)}/><MetricCard label="PREDICTED CLASS" value={prediction.explanation.prediction_context.predicted_class}/></div><div className="mt-5 grid gap-5 lg:grid-cols-2"><LocalContributionList title="Pushed toward positive class" items={prediction.explanation.contributions.filter(item=>item.direction==='toward_positive')}/><LocalContributionList title="Pushed toward negative class" items={prediction.explanation.contributions.filter(item=>item.direction==='toward_negative')}/></div><Notice tone="amber">{prediction.explanation.limitations[0]}</Notice></div>}{!prediction?.explanation&&prediction?.influence&&<div className="mt-5"><h3 className="font-semibold">Local feature influence</h3><InfluenceBars items={prediction.influence}/><Notice tone="amber">Feature influence reflects model behavior, not biological causation or clinical diagnosis.</Notice></div>}<Link className="btn btn-outline mt-4" to="/explainability">Inspect model explanation <ArrowRight size={13}/></Link></Card>
  </div>

  <Card title="Continue the research investigation" description="Move from this prediction to existing results, diagnostics, explanation, robustness, quantum, and provenance evidence."><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[
   ['/comparison','Research Results Center',BarChart3],['/comparison','Diagnostic Evidence',Brain],['/explainability','Explainability',Brain],['/robustness','Robustness',ShieldAlert],['/quantum','Quantum Evidence',Atom],['/experiments/'+currentModel.experiment_id,'Evidence Package',FileText],['/experiments/'+currentModel.experiment_id,'Experiment Lineage',GitBranch]
  ].map(([path,copy,Icon])=><Link className="group flex items-center gap-3 rounded-xl border p-4 hover:bg-primary/5" to={String(path)} key={String(copy)}><Icon size={16} className="text-primary"/><strong className="flex-1 text-xs">{String(copy)}</strong><ArrowRight size={13} className="muted group-hover:text-primary"/></Link>)}</div></Card>
 </div>;
}
