import {Link} from 'react-router-dom';
import {ArrowRight,Atom,BarChart3,Brain,FileText,GitBranch,ShieldAlert} from 'lucide-react';
import {Badge,Card} from './ui';
import {EmptyState,JsonDisclosure,MetricCard,Notice} from './Shared';
import {RobustnessDeltaChart,RobustnessTrendChart} from './Charts';
import {metric,modelLabels,shortId} from '../utils/format';
import type {Dataset,Experiment,MetricName,ModelRecord,RobustnessEvidence,SubgroupStudy,VerifiedRobustnessResult} from '../types/qhealth';

type Props={mode:'live'|'verified';experiment?:Experiment;dataset?:Dataset;models:ModelRecord[];liveRecords?:RobustnessEvidence[];verifiedRecords?:VerifiedRobustnessResult[];method?:string;subgroupStudies?:SubgroupStudy[]};
type Row={id:string;modelId:string;modelType:ModelRecord['model_type'];status:string;scenario:string;level?:number;sampleCount?:number;baseline:Partial<Record<MetricName,number|null>>;degraded:Partial<Record<MetricName,number|null>>;delta:Partial<Record<MetricName,number|null>>;metadata?:Record<string,unknown>;limitations:string[];source:unknown};
const metrics:MetricName[]=['accuracy','precision','recall','sensitivity','specificity','f1','roc_auc'];
const finite=(value:unknown):value is number=>typeof value==='number'&&Number.isFinite(value);
const signed=(value:number|null|undefined)=>finite(value)?`${value>0?'+':''}${(value*100).toFixed(2)} pp`:'Not recorded';

export function RobustnessEvidenceLab({mode,experiment,dataset,models,liveRecords=[],verifiedRecords=[],method,subgroupStudies=[]}:Props){
 const liveRows:Row[]=liveRecords.map((record,index)=>({id:record.id||`${record.model_id}-${record.perturbation_type}-${record.perturbation_level}-${index}`,modelId:record.model_id,modelType:record.model_type,status:record.status,scenario:record.perturbation_type,level:record.perturbation_level,sampleCount:record.sample_count,baseline:record.baseline_metrics,degraded:record.perturbed_metrics||{},delta:record.degradation_delta,metadata:record.perturbation_metadata||undefined,limitations:record.limitations||[],source:record}));
 const verifiedRows:Row[]=verifiedRecords.map((record,index)=>({id:`${record.model_id}-${record.condition}-${index}`,modelId:record.model_id,modelType:record.model_type,status:'evaluated',scenario:record.condition,level:typeof record.configuration.level==='number'?record.configuration.level:undefined,sampleCount:record.baseline.sample_count,baseline:record.baseline,degraded:record.degraded,delta:record.delta,metadata:record.perturbation,limitations:[],source:record}));
 const rows=[...liveRows,...verifiedRows];
 const trendRecords=rows.filter(row=>typeof row.level==='number').map(row=>({modelId:row.modelId,modelType:row.modelType,scenario:row.scenario,level:row.level as number,delta:row.delta}));
 const evaluated=rows.filter(row=>row.status==='evaluated');
 const scenarioCount=new Set(rows.map(row=>`${row.scenario}:${row.level??''}`)).size;
 const modelCount=new Set(rows.map(row=>row.modelId)).size;
 const available=rows.length>0;
 const chartRecords=liveRecords.filter(record=>record.status==='evaluated');
 const biggest=evaluated.filter(row=>finite(row.delta.accuracy)).sort((a,b)=>(a.delta.accuracy as number)-(b.delta.accuracy as number))[0];
 const smallest=evaluated.filter(row=>finite(row.delta.accuracy)).sort((a,b)=>Math.abs(a.delta.accuracy as number)-Math.abs(b.delta.accuracy as number))[0];
 const quantumRow=evaluated.find(row=>['vqc','qsvc','qnn','hybrid_pennylane_torch'].includes(row.modelType));
 const classicalRow=evaluated.find(row=>!['vqc','qsvc','qnn','hybrid_pennylane_torch'].includes(row.modelType));
 const limitations=[...new Set([...liveRecords.flatMap(record=>record.limitations||[]),...subgroupStudies.flatMap(study=>study.limitations||[]),mode==='verified'?'Packaged robustness evidence is read-only and no perturbation study is executed on page load.':'Only persisted or explicitly requested bounded studies are shown.'])];
 return <div className="space-y-5">
  <Card title="Robustness overview" description="Persisted evidence under the exact evaluated perturbation conditions; no model is refit and no threshold is reselected.">
   <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><MetricCard label="EXPERIMENT" value={experiment?shortId(experiment.id):'Not recorded'} detail={experiment?.status||'Status not recorded'}/><MetricCard label="DATASET" value={dataset?.name||experiment?.dataset_id||'Not recorded'} detail={dataset?.sha256?`SHA-256 ${dataset.sha256}`:'Hash not recorded'}/><MetricCard label="MODELS" value={available?modelCount:'Not evaluated'} detail={`${models.length} model records in context`}/><MetricCard label="SCENARIOS" value={available?scenarioCount:'Not evaluated'} detail={`${rows.length} persisted records`}/><MetricCard label="EVIDENCE STATUS" value={available?'AVAILABLE':'NOT EVALUATED'} detail={mode==='verified'?'Verified / precomputed':'Persisted live experiment'}/><MetricCard label="METHOD" value={method||'Not recorded'} detail="Backend-provided study method"/><MetricCard label="SOURCE" value={mode==='verified'?'Packaged evidence':'Experiment records'} detail="No automatic study execution"/><MetricCard label="SUBGROUP STUDIES" value={subgroupStudies.length||'Not available'} detail="Persisted studies only"/></div>
  </Card>
  {!available?<EmptyState title="Robustness evidence not evaluated">No persisted robustness records are available for this experiment. Opening this view does not create a study.</EmptyState>:<>
   {rows.filter(row=>row.status!=='evaluated').map(row=><Notice tone="amber" key={`${row.id}-status`}><strong>{row.status.replaceAll('_',' ')}:</strong> {(row.source as RobustnessEvidence).reason||'This condition was not evaluated; no missing value is replaced with zero.'}</Notice>)}
   {chartRecords.length>0&&<Card title="Observed degradation under controlled perturbation" description="Delta is perturbed minus baseline. Negative changes remain negative."><RobustnessDeltaChart records={chartRecords}/></Card>}
   {trendRecords.length>1&&<Card title="Robustness response by perturbation level" description="Shown only when multiple persisted perturbation levels are available; no intermediate points are fabricated."><RobustnessTrendChart records={trendRecords}/></Card>}
   <Card title="Baseline vs degraded results" description="Exact persisted measurements. Percentage-point deltas are displayed from backend-provided degradation values."><div className="table-wrap overflow-x-auto"><table className="data-table min-w-[1100px]"><thead><tr><th>Model</th><th>Scenario</th><th>Samples</th><th>Baseline accuracy</th><th>Degraded accuracy</th><th>Δ accuracy</th><th>Baseline ROC-AUC</th><th>Degraded ROC-AUC</th><th>Δ ROC-AUC</th><th>Status</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><strong>{modelLabels[row.modelType]}</strong></td><td>{row.scenario.replaceAll('_',' ')}{row.level!==undefined?` · ${row.level}`:''}</td><td>{row.sampleCount??'Not recorded'}</td><td>{metric(row.baseline.accuracy)}</td><td>{metric(row.degraded.accuracy)}</td><td>{signed(row.delta.accuracy)}</td><td>{metric(row.baseline.roc_auc)}</td><td>{metric(row.degraded.roc_auc)}</td><td>{signed(row.delta.roc_auc)}</td><td><Badge tone={row.status==='evaluated'?'green':'amber'}>{row.status.replaceAll('_',' ').toUpperCase()}</Badge></td></tr>)}</tbody></table></div></Card>
   {quantumRow&&classicalRow&&<Card title="Paired observed differences" description="Displayed difference is quantum/hybrid degradation delta minus classical degradation delta. These are descriptive measurements, not a winner or advantage claim."><div className="table-wrap overflow-x-auto"><table className="data-table"><thead><tr><th>Metric</th><th>Classical Δ</th><th>Quantum / hybrid Δ</th><th>Observed difference</th></tr></thead><tbody>{metrics.map(name=>{const classical=classicalRow.delta[name];const quantum=quantumRow.delta[name];const difference=finite(classical)&&finite(quantum)?quantum-classical:null;return <tr key={name}><td>{name.replaceAll('_',' ')}</td><td>{signed(classical)}</td><td>{signed(quantum)}</td><td>{signed(difference)}</td></tr>})}</tbody></table></div></Card>}
   <div className="grid gap-5 lg:grid-cols-2"><Card title="Robustness by model" description="Observed changes across displayed scenarios; smaller change in one condition is not a general robustness claim."><div className="space-y-3">{models.filter(model=>rows.some(row=>row.modelId===model.id)).map(model=>{const own=rows.filter(row=>row.modelId===model.id);return <div className="rounded-xl border p-3" key={model.id}><div className="flex justify-between gap-3"><strong>{modelLabels[model.model_type]}</strong><Badge tone="blue">{own.length} records</Badge></div>{own.map(row=><div className="mt-2 flex justify-between text-xs" key={row.id}><span className="muted">{row.scenario.replaceAll('_',' ')}</span><strong>Accuracy {signed(row.delta.accuracy)} · ROC-AUC {signed(row.delta.roc_auc)}</strong></div>)}</div>})}</div></Card><Card title="Robustness by scenario" description="Scenario meaning and affected-input metadata come only from persisted backend evidence."><div className="space-y-3">{[...new Set(rows.map(row=>row.scenario))].map(scenario=>{const own=rows.filter(row=>row.scenario===scenario);return <div className="rounded-xl border p-3" key={scenario}><div className="flex justify-between gap-3"><strong>{scenario.replaceAll('_',' ')}</strong><Badge tone="purple">{own.length} model results</Badge></div><p className="mt-2 text-xs muted">Samples: {[...new Set(own.map(row=>row.sampleCount).filter(Boolean))].join(', ')||'Not recorded'} · Levels: {[...new Set(own.map(row=>row.level).filter(value=>value!==undefined))].join(', ')||'Not recorded'}</p><JsonDisclosure label="Persisted perturbation metadata" value={own.map(row=>({model:modelLabels[row.modelType],metadata:row.metadata||'not_recorded'}))}/></div>})}</div></Card></div>
   <Card title="Observed robustness findings" description="Deterministic statements limited to the displayed experiment."><ul className="space-y-2 text-sm">{biggest&&<li>• {modelLabels[biggest.modelType]} showed the largest displayed accuracy decrease: {signed(biggest.delta.accuracy)} under {biggest.scenario.replaceAll('_',' ')}.</li>}{smallest&&<li>• {modelLabels[smallest.modelType]} showed the smallest absolute displayed accuracy change: {signed(smallest.delta.accuracy)} under {smallest.scenario.replaceAll('_',' ')}.</li>}<li>• {rows.length} robustness records cover {modelCount} models and {scenarioCount} evaluated conditions.</li></ul></Card>
  </>}
  <Card title="Persisted subgroup evidence" description="Descriptive subgroup outputs only; no fairness, clinical-equity, or population-generalization claim.">{subgroupStudies.length?<div className="space-y-5">{subgroupStudies.map(study=>{const groups=study.subgroups?.length?study.subgroups:study.subgroups_results||[];return <div className="rounded-xl border p-4" key={study.id}><div className="flex flex-wrap items-center justify-between gap-3"><div><strong>{study.subgroup_field}</strong><p className="text-xs muted">{study.id} · {study.status}</p></div><Badge tone={study.status==='completed'?'green':'amber'}>{study.status.toUpperCase()}</Badge></div><div className="table-wrap mt-3 overflow-x-auto"><table className="data-table"><thead><tr><th>Subgroup</th><th>Status</th><th>n</th><th>Accuracy</th><th>F1</th><th>ROC-AUC</th><th>Observed ROC-AUC difference</th></tr></thead><tbody>{groups.map(group=>{const comparison=study.comparisons.find(item=>item.subgroup_id===group.id);return <tr key={group.id}><td>{group.label}</td><td>{group.status}</td><td>{group.population.n}</td><td>{metric(group.metrics.accuracy?.value)}</td><td>{metric(group.metrics.f1?.value)}</td><td>{metric(group.metrics.roc_auc?.value)}</td><td>{signed(comparison?.deltas.roc_auc)}</td></tr>})}</tbody></table></div></div>})}</div>:<Notice tone="amber">Subgroup evidence is not available for this experiment. No subgroup study is created automatically.</Notice>}</Card>
  <Card title="Evidence limitations" description="These results are bounded to the recorded samples and evaluated perturbations."><ul className="space-y-2 text-xs muted">{limitations.map(item=><li key={item}>• {item}</li>)}<li>• A limited perturbation study does not establish generalization to untested distribution shifts.</li><li>• Observed subgroup differences do not establish fairness, causality, or clinical utility.</li></ul></Card>
  <Card title="Continue the research investigation"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['/comparison','Research Results Center',BarChart3],['/comparison','Diagnostic Evidence',Brain],['/quantum','Quantum Evidence',Atom],['/explainability','Explainability',Brain],['/prediction','Prediction',ArrowRight],['/experiments/'+(experiment?.id||''),'Evidence Package',FileText],['/experiments/'+(experiment?.id||''),'Experiment Lineage',GitBranch],['/robustness','Robustness',ShieldAlert]].map(([path,label,Icon])=><Link className="flex items-center gap-3 rounded-xl border p-4 hover:bg-primary/5" to={String(path)} key={String(label)}><Icon size={15} className="text-primary"/><strong className="text-xs">{String(label)}</strong></Link>)}</div></Card>
 </div>;
}
