import {useEffect,useRef,useState} from 'react';
import {Search,ArrowRight,Database,Brain,FlaskConical,X} from 'lucide-react';
import {useNavigate} from 'react-router-dom';
import {api} from '../lib/api';
import {shortId} from '../utils/format';
type Result={type:'dataset'|'model'|'experiment';id:string;label:string;meta:string;path:string};
export function SearchBar({compact=false}:{compact?:boolean}){
 const nav=useNavigate();const [q,setQ]=useState('');const [open,setOpen]=useState(false);const [results,setResults]=useState<Result[]>([]);const ref=useRef<HTMLDivElement>(null);
 useEffect(()=>{const timer=setTimeout(async()=>{if(q.trim().length<2){setResults([]);return}const [ds,ms,es]=await Promise.all([api.get<any[]>('/datasets').catch(()=>[]),api.get<any[]>('/models').catch(()=>[]),api.get<any[]>('/experiments').catch(()=>[])]);const needle=q.toLowerCase();const out:Result[]=[];ds.filter(d=>String(d.name).toLowerCase().includes(needle)).slice(0,3).forEach(d=>out.push({type:'dataset',id:d.id,label:d.name,meta:String(d.provenance?.row_count||0)+' samples',path:'/datasets'}));ms.filter(m=>(String(m.model_type)+' '+String(m.id)).toLowerCase().includes(needle)).slice(0,3).forEach(m=>out.push({type:'model',id:m.id,label:String(m.model_type).replaceAll('_',' '),meta:'Model '+shortId(m.id),path:'/comparison'}));es.filter(e=>(String(e.id)+' '+String(e.status)).toLowerCase().includes(needle)).slice(0,3).forEach(e=>out.push({type:'experiment',id:e.id,label:'Experiment '+shortId(e.id),meta:String(e.status),path:'/experiments/'+e.id}));setResults(out.slice(0,8))},180);return()=>clearTimeout(timer)},[q]);
 useEffect(()=>{const handler=(e:MouseEvent)=>{if(ref.current&&!ref.current.contains(e.target as Node))setOpen(false)};document.addEventListener('mousedown',handler);return()=>document.removeEventListener('mousedown',handler)},[]);
 return <div ref={ref} className={'research-search '+(compact?'compact':'')}><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 muted"/><input value={q} onChange={e=>{setQ(e.target.value);setOpen(true)}} onFocus={()=>setOpen(true)} placeholder="Search datasets, models, experiments..."/><span className="search-kbd">⌘K</span>{q&&<button className="absolute right-16 top-1/2 -translate-y-1/2 muted" onClick={()=>setQ('')} aria-label="Clear search"><X size={13}/></button>}{open&&q.length>=2&&<div className="absolute left-0 right-0 top-[44px] z-50 overflow-hidden rounded-xl border bg-card shadow-2xl">{results.length?results.map(r=><button key={r.type+r.id} className="flex w-full items-center gap-3 px-4 py-3 text-left hover:bg-muted" onClick={()=>{setQ('');setOpen(false);nav(r.path)}}>{r.type==='dataset'?<Database size={15}/>:r.type==='model'?<Brain size={15}/>:<FlaskConical size={15}/>}<span className="min-w-0 flex-1"><strong className="block capitalize">{r.label}</strong><small className="muted">{r.meta}</small></span><ArrowRight size={14}/></button>):<div className="p-4 text-sm muted text-center">No research record found.</div>}</div>}</div>;
}