import type {ReactNode} from 'react';
import {Link} from 'react-router-dom';
import {AlertTriangle,Atom,Database,LoaderCircle} from 'lucide-react';
import {Card,Badge,Select} from './ui';
import {modelLabels,metric,shortId} from '../utils/format';
import type {Dataset,ModelRecord,Metrics,MetricName} from '../types/qhealth';

export function PageHeader({eyebrow,title,description,actions}:{eyebrow:string;title:string;description:string;actions?:ReactNode}){return <div className="page-hero"><div className="flex flex-wrap items-end justify-between gap-5"><div><div className="eyebrow">{eyebrow}</div><h1 className="headline">{title}</h1><p className="subhead">{description}</p></div>{actions&&<div className="flex flex-wrap gap-2">{actions}</div>}</div></div>}
export function StatusBadge({value}:{value:string}){const tone=['ready','succeeded','completed'].includes(value)?'green':['failed','cancelled','interrupted'].includes(value)?'red':value==='running'||value==='queued'?'amber':'blue';return <Badge tone={tone}>{value.replaceAll('_',' ')}</Badge>}
export function MetricCard({label,value,detail,icon}:{label:string;value:ReactNode;detail?:string;icon?:ReactNode}){return <Card className="min-h-[145px]"><div className="flex items-start justify-between"><span className="metric-label">{label}</span>{icon&&<span className="rounded-lg bg-primary/8 p-2 text-primary">{icon}</span>}</div><div className="mt-5 metric-value">{value}</div>{detail&&<div className="mt-2 metric-detail">{detail}</div>}</Card>}
export function ErrorBanner({error}:{error?:string}){return error?<div className="error-callout flex items-start gap-3"><AlertTriangle size={16}/><span className="text-sm">{error}</span></div>:null}
export function EmptyState({title,children}:{title:string;children:ReactNode}){return <Card className="py-12 text-center"><div className="mx-auto mb-3 grid h-11 w-11 place-items-center rounded-full bg-muted"><Atom size={18}/></div><h3 className="font-semibold">{title}</h3><p className="mt-1 text-sm muted">{children}</p></Card>}
export function Loading(){return <div className="glass-card flex items-center gap-2 p-5 text-sm muted"><LoaderCircle size={15} className="animate-spin"/>Loading research data…</div>}
export function Notice({children,tone='blue'}:{children:ReactNode;tone?:'blue'|'amber'|'green'}){return <div className={tone==='amber'?'callout border-amber-500/20 bg-amber-500/5':tone==='green'?'callout border-emerald-500/20 bg-emerald-500/5':'callout'}>{children}</div>}
export function JsonDisclosure({label,value}:{label:string;value:unknown}){return <details className="mt-4 rounded-xl border bg-muted/30 p-3"><summary className="cursor-pointer text-xs font-semibold">{label}</summary><pre className="mt-3 max-h-[360px] overflow-auto whitespace-pre-wrap break-all text-[10px] leading-relaxed muted">{JSON.stringify(value,null,2)}</pre></details>}
export function ModelSelect({models,value,onChange,quantumOnly=false}:{models:ModelRecord[];value:string;onChange:(v:string)=>void;quantumOnly?:boolean}){const available=models.filter(m=>m.status==='ready'&&(!quantumOnly||['vqc','qsvc','qnn'].includes(m.model_type)));return <label className="field"><span>Registered model</span><Select value={value} onChange={e=>onChange(e.target.value)}><option value="">Choose completed model</option>{available.map(m=><option key={m.id} value={m.id}>{modelLabels[m.model_type]} · {shortId(m.id)}</option>)}</Select></label>}
export function MetricRow({label,value}:{label:string;value:number|null|undefined}){return <div className="flex items-center justify-between border-b py-2 last:border-b-0"><span className="text-xs muted">{label}</span><strong className="mono text-xs">{metric(value)}</strong></div>}
export const metricNames:MetricName[]=['accuracy','precision','recall','sensitivity','specificity','f1','roc_auc'];
export function MetricGrid({metrics}:{metrics:Metrics}){return <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{metricNames.map(name=><div className="rounded-xl border p-3" key={name}><span className="metric-label">{name.replace('_',' ')}</span><strong className="mt-2 block text-lg">{metric(metrics[name],name!=='roc_auc')}</strong></div>)}</div>}
export function DatasetSelect({value,onChange,datasets}:{value:string;onChange:(v:string)=>void;datasets:Dataset[]}){return <Card className="flex flex-wrap items-end gap-3 py-4"><label className="field min-w-[260px] flex-1"><span>Active research dataset</span><Select value={value} onChange={e=>onChange(e.target.value)}><option value="">Select a dataset</option>{datasets.map(d=><option value={d.id} key={d.id}>{d.name} · {d.provenance.row_count} samples</option>)}</Select></label><Link className="btn btn-outline" to="/datasets"><Database size={14}/>Manage datasets</Link></Card>}
