import {fireEvent, render, screen, waitFor} from '@testing-library/react';
import {MemoryRouter} from 'react-router-dom';
import {afterEach, beforeEach, describe, expect, it, vi} from 'vitest';
import {DraftProvider} from '../hooks/ExperimentDraft';
import QuantumCircuit from '../pages/QuantumCircuit';
const circuit = {model_type: 'vqc', execution_kind: 'exact local quantum simulation', backend: 'statevector', qubits: 4, logical_depth: 8, parameter_count: 12, gate_counts: {rz: 4, cx: 3}, text: 'q[0]: ──', gates: [{name: 'rz', qubits: [0], parameters: ['x[0]']}], limitation: 'Structural circuit only; this endpoint does not execute a circuit.'};
function response(body: unknown, ok = true): Response {return {ok, json: async () => body} as Response;}
function renderPage() {return render(<MemoryRouter><DraftProvider><QuantumCircuit/></DraftProvider></MemoryRouter>);}
describe('Quantum Lab environment', () => {
  beforeEach(() => {localStorage.clear(); vi.stubGlobal('fetch', vi.fn().mockImplementation((input: RequestInfo | URL) => String(input).endsWith('/quantum/capabilities') ? Promise.resolve(response({available: true, runtime_verified: false, execution: 'local quantum simulation only'})) : Promise.resolve(response([]))));});
  afterEach(() => {vi.unstubAllGlobals(); localStorage.clear();});
  it('renders the Quantum Lab workflow, supported model controls, and real transitions', async () => {renderPage(); expect(screen.getByRole('heading', {name: 'Quantum circuit'})).toBeInTheDocument(); expect(screen.getByRole('navigation', {name: 'Quantum Lab workflow'})).toBeInTheDocument(); for (const label of ['VQC: feature map + ansatz', 'QSVC: kernel feature map', 'QNN: sampler neural network']) expect(screen.getByText(label)).toBeInTheDocument(); expect(screen.getByRole('link', {name: /Configure in Model Lab/})).toHaveAttribute('href', '/training'); expect(screen.getByRole('link', {name: /Research Studio/})).toHaveAttribute('href', '/experiments'); await waitFor(() => expect(screen.getByText(/No circuit representation yet/)).toBeInTheDocument());});
  it('renders backend circuit metadata without implying execution', async () => {vi.stubGlobal('fetch', vi.fn().mockImplementation((input: RequestInfo | URL, init?: RequestInit) => {const url = String(input); if (url.endsWith('/quantum/capabilities')) return Promise.resolve(response({available: true, runtime_verified: false, execution: 'local quantum simulation only'})); if (url.endsWith('/quantum/circuit') && init?.method === 'POST') return Promise.resolve(response(circuit)); return Promise.resolve(response([]));})); renderPage(); fireEvent.click(screen.getByRole('button', {name: /Generate circuit representation/})); await waitFor(() => expect(screen.getByText(/exact local quantum simulation/)).toBeInTheDocument()); expect(screen.getByText('4')).toBeInTheDocument(); expect(screen.getAllByText(/does not execute a circuit/).length).toBeGreaterThan(0); expect(screen.getByText(/measure quantum advantage/i)).toBeInTheDocument();});
  it('shows the unavailable capability state from the backend', async () => {vi.stubGlobal('fetch', vi.fn().mockImplementation((input: RequestInfo | URL) => String(input).endsWith('/quantum/capabilities') ? Promise.resolve(response({available: false, runtime_verified: false, execution: 'quantum dependencies unavailable'})) : Promise.resolve(response([])))); renderPage(); await waitFor(() => expect(screen.getByText('Unavailable')).toBeInTheDocument()); expect(screen.getByRole('button', {name: /Generate circuit representation/})).toBeDisabled();});
});
