export type ModelKind = 'logistic_regression' | 'svm' | 'random_forest' | 'vqc' | 'qsvc' | 'qnn';
export type MetricName = 'accuracy' | 'precision' | 'recall' | 'sensitivity' | 'specificity' | 'f1' | 'roc_auc';

export interface PipelineConfig {
  imputer:'median'|'mean'|'most_frequent'; scaler:'standard'|'minmax'|'robust'|'none';
  outlier_strategy:'none'|'clip_quantiles'; lower_quantile:number; upper_quantile:number;
  log_features:string[]; ratios:{name:string;numerator:string;denominator:string}[];
  selection:'none'|'anova'|'mutual_info'|'variance'; k_features:number; variance_threshold:number;
  pca_components:number|null; pca_whiten:boolean; angle_scaling:boolean;
}
export interface QuantumConfig {
  backend:'statevector'|'aer'; qubits:number; feature_map_reps:number; ansatz_reps:number;
  entanglement:'linear'|'full'; optimizer:'COBYLA'|'SPSA'; maxiter:number; shots:number; noise_probability:number;
}
export interface TrainingConfig {
  dataset_id:string; features:string[]|null; models:ModelKind[]; pipeline:PipelineConfig; quantum:QuantumConfig;
  parameters:{logistic_c:number;svm_c:number;svm_kernel:'rbf'|'linear';forest_trees:number;forest_max_depth:number|null;class_weight:'balanced'|null};
  seed:number; test_size:number; cv_folds:number; max_samples:number|null; duplicate_policy:'reject'|'drop_exact';
  probability_threshold:number; threshold_strategy:'fixed'|'target_sensitivity'; target_sensitivity:number;
  calibration:'none'|'sigmoid'|'isotonic'; calibration_folds:number;
}
export interface Provenance {name:string;domain:string;source:string;source_url:string|null;version:string;target:string;positive_label:string;negative_label:string;features:string[];numeric_features:string[];categorical_features:string[];row_count:number;feature_count:number;class_distribution:Record<string,number>;target_classes:string[];is_demo:boolean;dataset_hash:string;license:string|null;origin?:'built_in'|'uploaded';dataset_status?:string;target_type?:string;recommended_duplicate_policy?:'reject'|'drop_exact';[key:string]:unknown}
export interface Quality {scope:string;row_count:number;feature_count:number;class_distribution:Record<string,number>;minority_fraction:number;class_imbalance:boolean;missing_values:Record<string,number>;infinite_values:Record<string,number>;duplicate_rows:number;duplicate_feature_rows:number;constant_features:string[];low_variance_features:string[];suspiciously_predictive_features:string[];identifier_features:string[];highly_correlated_pairs:{feature_a:string;feature_b:string;absolute_correlation:number}[];warnings:string[];blockers:string[];distributions:Record<string,unknown>[];invalid_numeric_values:string}
export interface Dataset {id:string;name:string;sha256:string;provenance:Provenance;quality:Quality;created_at:string}
export interface TargetCandidate {column:string;score:number;confidence:'low'|'medium'|'high';target_type:string;class_labels:string[];class_distribution:Record<string,number>;unique_values:number;missing_fraction:number;eligible_for_current_pipeline:boolean;reasons:string[];penalties:string[];position:number}
export interface DatasetInspection {filename:string;sha256:string;row_count:number;column_count:number;columns:string[];schema:{name:string;type:string;missing_count:number;unique_count:number}[];detected_target:string|null;target_type:string|null;confidence_score:number;confidence:'low'|'medium'|'high';selection_method:string;class_labels:string[];class_distribution:Record<string,number>;positive_label:string|null;positive_label_confidence:number;positive_label_reason:string;requires_manual_target:boolean;requires_positive_label:boolean;heuristic_notice:string;candidates:TargetCandidate[]}
export interface DemoReadiness {status:'ready'|'requires_processing';instant_demo_available:boolean;artifact_version:string|null;experiment_id:string|null;model_ids:string[];verified_dataset_hash:string|null;verified_artifact_manifest_hash:string|null;unavailable_reason?:string|null}
export interface DatasetLibraryItem {slug:string;name:string;domain:string;description:string;source:string;source_url:string;version:string;license:string;license_url:string;attribution:string;target:string;target_type:'binary_classification';positive_label:string;negative_label:string;row_count:number;feature_count:number;class_labels:string[];sha256:string;normalization:string[];recommended_duplicate_policy:'reject'|'drop_exact';origin:'built_in';dataset_status:'available';demo_readiness:DemoReadiness}
export interface Job {id:string;experiment_id:string;status:string;progress:number;state:string;errors:Record<string,unknown>[];created_at:string;updated_at:string}
export interface Experiment {id:string;dataset_id:string;parent_id:string|null;status:string;config:TrainingConfig;summary:Record<string,unknown>;created_at:string}
export interface Metrics {accuracy:number|null;precision:number|null;recall:number|null;sensitivity:number|null;specificity:number|null;f1:number|null;roc_auc:number|null;true_positive:number;true_negative:number;false_positive:number;false_negative:number;confusion_matrix:number[][];sample_count:number;roc_curve:{fpr:number[];tpr:number[];thresholds:(number|null)[]}|null;undefined_metrics:string[]}
export interface ThresholdPoint {threshold:number;sensitivity:number|null;specificity:number|null;precision:number|null;recall:number|null;f1:number|null;accuracy:number|null;roc_auc:number|null}
export interface OperatingPoint {selection_strategy:'fixed'|'target_sensitivity';target_sensitivity:number|null;target_specificity:number|null;selected_threshold:number|null;threshold_units:string;threshold_feasible:boolean;threshold_source:string;validation_metrics:ThresholdPoint|null;holdout_metrics:Partial<Record<MetricName,number|null>>|null;number_of_oof_samples:number|null;cv_fold_count:number|null;curve:ThresholdPoint[];interpretation:string;infeasible_reason?:string|null}
export interface ModelMetrics {training:Metrics;test:Metrics;validation:{folds:Metrics[];summary:Record<MetricName,{mean:number|null;std:number|null;valid_folds:number}>;std_definition:string};timing:{final_training_seconds:number;cv_total_seconds:number;cv_fold_seconds:number[];test_inference_seconds:number;test_inference_seconds_per_sample:number};calibration:Record<string,unknown>;operating_point?:OperatingPoint}
export interface ModelRecord {id:string;experiment_id:string;dataset_id:string;model_type:ModelKind;status:string;details:Record<string,unknown>;metrics:Partial<ModelMetrics>;created_at:string}
export interface ExperimentDetail {experiment:Experiment;models:ModelRecord[];jobs:Job[]}
export interface Preview {train_count:number;test_count:number;input_features:string[];selected_features:string[];output_features:string[];selection_scores:{feature:string;score:number|null;selected:boolean}[];pca_explained_variance:number[];pca_loadings:number[][];split_hash:string;stages:string[];warnings:string[]}
export interface Circuit {model_type:string;execution_kind:string;backend:string;qubits:number;logical_depth:number;parameter_count:number;gate_counts:Record<string,number>;text:string;gates:{name:string;qubits:number[];parameters:string[]}[];limitation:string}
export interface Influence {feature:string;magnitude:number;std?:number;delta_plus?:number;delta_minus?:number;perturbation?:string}
export interface Explanation {id:string;model_id:string;method:string;created_at:string;result:{title:string;scope:string;sample_count:number;units:string;influence:Influence[];elapsed_seconds:number;limitations:string[]}}
export interface Prediction {model_id:string;model_type:ModelKind;positive_label:string;negative_label:string;probability_status:string;decision_rule:string;threshold_source:string;risk_thresholds:[number,number];predictions:{sample:string;predicted_class:string;probability_positive:number|null;decision_score:number|null;research_risk_category:string|null}[];influence:Influence[]|null;limitations:string[];disclaimer:string}
export interface EvidenceValue {classical:number|null;quantum:number|null;delta_quantum_minus_classical:number|null}
export interface EvidenceTiming {final_training_seconds:number|null;cv_total_seconds:number|null;cv_mean_fold_seconds:number|null;test_inference_seconds:number|null;test_inference_seconds_per_sample:number|null}
export type PerturbationType='missingness'|'gaussian_noise'|'outliers'|'categorical';
export interface RobustnessScenario {perturbation_type:PerturbationType;level:number}
export interface RobustnessEvidence {id?:string;status:'evaluated'|'not_applicable'|'failed';reason:string|null;experiment_id:string;dataset_id:string;dataset_hash:string;split_hash:string|null;model_id:string;model_type:ModelKind;perturbation_type:PerturbationType;perturbation_level:number;random_seed:number;sample_count:number;baseline_metrics:Metrics;perturbed_metrics:Metrics|null;degradation_delta:Record<MetricName,number|null>;relative_degradation:Record<MetricName,number|null>;undefined_metrics:Record<string,string>;threshold_used:number;threshold_source:string;preprocessing_context:Record<string,unknown>;perturbation_metadata:Record<string,unknown>|null;execution_timing:{baseline_inference_seconds:number;perturbed_inference_seconds:number|null};limitations:string[];reproducibility_metadata:Record<string,unknown>;created_at?:string}
export interface RobustnessResponse {experiment_id:string;dataset_id:string;sample_count:number;model_count:number;condition_count:number;results:RobustnessEvidence[];limitations:string[]}
export interface RobustnessPairScenario {perturbation_type:PerturbationType;perturbation_level:number;random_seed:number;sample_count:number;classical:RobustnessEvidence|null;quantum:RobustnessEvidence|null;delta_difference_quantum_minus_classical:Record<MetricName,number|null>;interpretation:string}
export interface EvidencePair {quantum_model:string;classical_model:string;quantum_type:ModelKind;classical_type:ModelKind;performance:Record<MetricName,EvidenceValue>;computational_cost:{classical:EvidenceTiming;quantum:EvidenceTiming;deltas_quantum_minus_classical:EvidenceTiming;semantics:string};quantum_resources:{backend:string|null;execution_kind:string|null;qubits:number|null;shots:number|null;logical_depth:number|null;gate_counts:Record<string,number>|null;total_parameter_count:number|null;trainable_parameter_count:number|null;optimizer:string|null;optimizer_objective_evaluations:number|null;noise_probability:number|null;real_hardware:boolean;resource_semantics:string};fairness:{dataset_id:string;dataset_hash:string|null;experiment_id:string;split_hash:string|null;common_sample_count:number|null;source_sample_count:number|null;preprocessing_fingerprint:string|null;cv_fold_count:number|null;seed:number|null;threshold_strategy:string;controlled_comparison:boolean};operating_points:{classical:OperatingPoint;quantum:OperatingPoint};robustness:{status:string;note:string;scenarios?:RobustnessPairScenario[];limitations?:string[]};conclusion:string;limitations:string[];test_metric_delta_quantum_minus_classical:Record<MetricName,number|null>;final_training_seconds_delta:number|null}
export interface Comparison {experiment_id:string;dataset_id:string;models:ModelRecord[];pairs:EvidencePair[];split:Record<string,unknown>;comparison_fingerprint:string;conclusion:string;limitations:string[]}
export interface Health {status:string;version:string;mode:string;authentication_required:boolean;quantum:{available:boolean;runtime_verified:boolean;execution:string};disclaimer:string}
export interface SystemStatus {status:string;version:string;mode:string;database_available:boolean;storage_available:boolean;quantum:Health['quantum'];supported_models:{classical:string[];quantum:string[]};jobs:{queued:number;running:number;active:number};}
