import {BarChart3, ArrowRight} from 'lucide-react';
import {Link} from 'react-router-dom';
import {useEffect, useState} from 'react';
import {api} from '../services/api';
import {useLoad} from '../hooks/useLoad';
import type {Comparison as ComparisonResult, Experiment, MetricName} from '../types';
import {ConfusionMatrix, Empty, ErrorNotice, Field, JsonView, MetricGrid, Status, metricDefinitions} from '../components/Common';
import {ROCChart} from '../components/Charts';
import {Drawer, Disclosure} from '../components/Primitives';
import {metric, modelLabels, seconds, shortId} from '../utils/format';
import {ModelLabNote, ModelLabPage, ModelLabPanel, ModelLabResultHeader, ModelLabUnavailable} from '../components/ModelLab';

export default function Comparison() {
  const list = useLoad(() => api.get<Experiment[]>('/experiments')); const [id, setId] = useState(''); const [modelId, setModelId] = useState(''); const [metricDetail, setMetricDetail] = useState<MetricName>();
  useEffect(() => {if (!id && list.data?.length) setId(list.data[0].id);}, [list.data, id]);
  const result = useLoad<ComparisonResult | null>(() => id ? api.get(`/experiments/${id}/comparison`) : Promise.resolve(null), [id], 5000);
  const ready = result.data?.models.filter(m => m.status === 'ready') || []; const selected = ready.find(m => m.id === modelId) || ready[0];
  const names: MetricName[] = ['sensitivity', 'specificity', 'roc_auc', 'f1', 'accuracy', 'precision', 'recall']; const curves = ready.flatMap(m => m.metrics.test?.roc_curve ? [{name: modelLabels[m.model_type], ...m.metrics.test.roc_curve}] : []);
  const metricValue = metricDetail && selected?.metrics.test ? selected.metrics.test[metricDetail] : undefined;
  return <ModelLabPage currentPath="/comparison" step="02 / COMPARE" title="Model comparison" description="Place measured classical and quantum results under the same partitions, transformations and held-out evaluation conditions." actions={<Link className="button secondary" to="/explainability"><ArrowRight size={14} aria-hidden="true"/> Continue to Explainability</Link>}>
    <ModelLabPanel title="Comparison context" description="Select an experiment with shared comparison conditions."><Field label="Experiment with shared comparison conditions"><select value={id} onChange={e => {setId(e.target.value); setModelId('');}}><option value="">Select experiment</option>{list.data?.map(e => <option key={e.id} value={e.id}>{shortId(e.id)} / {e.status}</option>)}</select></Field><ErrorNotice message={list.error || result.error}/>{result.loading && id && <p className="loading-state" role="status">Loading measured comparison…</p>}{!list.loading && !list.data?.length && <ModelLabUnavailable title="No experiments available">Create a training experiment before comparing measured model outputs.</ModelLabUnavailable>}</ModelLabPanel>
    {result.data && <><ModelLabNote tone="warning">{result.data.conclusion}</ModelLabNote><ModelLabPanel title="Held-out test performance" description="Completed and failed models are shown as returned by the backend."><div className="table-scroll"><table><caption>Measured model comparison</caption><thead><tr><th scope="col">Model</th><th scope="col">Status</th>{names.map(n => <th scope="col" key={n}>{n.replace('_', '-')}</th>)}<th scope="col">Final train time</th><th scope="col">CV total time</th><th scope="col">Inference / sample</th></tr></thead><tbody>{result.data.models.map(m => <tr key={m.id}><td><button className="text-button" onClick={() => setModelId(m.id)}>{modelLabels[m.model_type]}</button></td><td><Status value={m.status}/></td>{names.map(n => <td key={n}>{metric(m.metrics.test?.[n], n !== 'roc_auc')}</td>)}<td>{seconds(m.metrics.timing?.final_training_seconds)}</td><td>{seconds(m.metrics.timing?.cv_total_seconds)}</td><td>{seconds(m.metrics.timing?.test_inference_seconds_per_sample)}</td></tr>)}</tbody></table></div>{!result.data.models.length && <Empty>No model has finished; completed and failed models will both be shown here.</Empty>}</ModelLabPanel>
    {selected?.metrics.test && <><ModelLabPanel title={`${modelLabels[selected.model_type]} / held-out metrics`} description="Select a model row to inspect its measured test result."><MetricGrid metrics={selected.metrics.test}/><div className="metric-guide" aria-label="Metric definitions">{names.map(name => <button type="button" className="metric-guide-item" key={name} onClick={() => setMetricDetail(name)}><span>{name.replace('_', '-').toUpperCase()}</span><b>{metric(selected.metrics.test?.[name], name !== 'roc_auc')}</b></button>)}</div></ModelLabPanel><div className="two-columns"><ModelLabPanel title="False positives and false negatives"><ConfusionMatrix metrics={selected.metrics.test}/></ModelLabPanel><ModelLabPanel title="ROC comparison"><ROCChart curves={curves}/></ModelLabPanel></div><ModelLabPanel title="Generalization: CV mean and standard deviation"><div className="table-scroll"><table><thead><tr><th>Metric</th><th>Training (resubstitution)</th><th>CV mean</th><th>CV sample SD</th><th>Held-out test</th></tr></thead><tbody>{names.map(n => <tr key={n}><td>{n}</td><td>{metric(selected.metrics.training?.[n], n !== 'roc_auc')}</td><td>{metric(selected.metrics.validation?.summary[n].mean, n !== 'roc_auc')}</td><td>{metric(selected.metrics.validation?.summary[n].std, n !== 'roc_auc')}</td><td>{metric(selected.metrics.test?.[n], n !== 'roc_auc')}</td></tr>)}</tbody></table></div><p>CV dispersion is not a confidence interval. Training performance is not evidence of real-world clinical performance.</p><JsonView value={selected.metrics.calibration} label="Separate probability calibration diagnostics"/></ModelLabPanel></>}
    <ModelLabPanel title="Classical–quantum interpretation" description="Neutral pairwise output from the backend; no superiority claim is inferred by the interface.">{result.data.pairs.length ? result.data.pairs.map((pair, i) => <div className="pair-summary" key={i}><h3>{pair.quantum_type.toUpperCase()} vs {pair.classical_type}</h3><p>{pair.conclusion}</p><JsonView value={pair} label="All metric differences and measured time difference"/></div>) : <Empty>A completed classical model and a completed quantum model are needed for a pairwise conclusion.</Empty>}<JsonView value={{split: result.data.split, fingerprint: result.data.comparison_fingerprint, limitations: result.data.limitations}} label="Comparison conditions and limitations"/></ModelLabPanel></>}
    {metricDetail && <Drawer open={Boolean(metricDetail)} onClose={() => setMetricDetail(undefined)} title={`${metricDetail.replace('_', '-').toUpperCase()} · Metric detail`}><div className="advanced-drawer-body"><Disclosure title="Definition" defaultOpen><p>{metricDefinitions[metricDetail]}</p></Disclosure><Disclosure title="Measured value" defaultOpen><dl><dt>Model</dt><dd>{selected ? modelLabels[selected.model_type] : 'Not selected'}</dd><dt>Evaluation stage</dt><dd>Held-out test</dd><dt>Value</dt><dd className="metric-detail-value">{metricValue === undefined ? 'Not available' : metric(metricValue, metricDetail !== 'roc_auc')}</dd></dl></Disclosure><Disclosure title="Interpretation"><p>Interpret this value only under the experiment’s shared dataset, split, preprocessing, and feature-space conditions. It is not a clinical validation measure.</p></Disclosure></div></Drawer>}
  </ModelLabPage>;
}
