import {ArrowLeft, Download, ExternalLink} from 'lucide-react';
import {Link, useParams} from 'react-router-dom';
import {api} from '../services/api';
import {useAction, useLoad} from '../hooks/useLoad';
import type {ExperimentDetail as Detail} from '../types';
import {ConfusionMatrix, Empty, ErrorNotice, JsonView, MetricGrid, Status} from '../components/Common';
import {dateTime, modelLabels, seconds, shortId} from '../utils/format';
import {ResearchStudioPage, StudioNextLinks, StudioPanel, StudioUnavailable} from '../components/ResearchStudio';
export default function ExperimentDetail() {
  const {id = ''} = useParams(); const result = useLoad(() => api.get<Detail>(`/experiments/${id}`), [id], 5000); const action = useAction();
  return <ResearchStudioPage step="02 / EVIDENCE" title={`Experiment ${shortId(id)}`} description="Inspect the configuration, model records, measured evaluation, provenance and limitations behind one research experiment." actions={<Link className="button secondary" to="/experiments"><ArrowLeft size={14} aria-hidden="true"/> All experiments</Link>}>
    <ErrorNotice message={result.error || action.error}/>{result.loading && <p className="loading-state" role="status">Loading experiment evidence…</p>}{result.data && <><StudioPanel title="Experiment context" description="Metadata and execution state are kept separate from measured scientific output."><div className="studio-detail-status"><Status value={result.data.experiment.status}/><span>{dateTime(result.data.experiment.created_at)}</span><button disabled={action.busy} onClick={() => void action.run(() => api.download(`/experiments/${id}/report?format=html`, `qhealth-${id}.html`))}><Download size={14} aria-hidden="true"/> Export HTML report</button><button className="secondary" disabled={action.busy} onClick={() => void action.run(() => api.download(`/experiments/${id}/report?format=json`, `qhealth-${id}.json`))}><Download size={14} aria-hidden="true"/> Export JSON</button></div><div className="studio-detail-grid"><div><h3>Provenance and partition record</h3><JsonView value={result.data.experiment.summary} label="Dataset, hash, split, versions and limitations"/>{result.data.experiment.parent_id && <Link to={`/experiments/${result.data.experiment.parent_id}`}>Open parent experiment</Link>}</div><div><h3>Exact experiment configuration</h3><JsonView value={result.data.experiment.config} label="All training and quantum settings"/>{result.data.jobs.map(j => <div className="studio-job" key={j.id}><Status value={j.status}/><p>{j.state}</p><progress value={j.progress} max={100}/><JsonView value={j.errors} label="Job failure records"/></div>)}</div></div></StudioPanel><div className="studio-disclaimer">Reports include the medical disclaimer, dataset provenance, measured metrics, computational measurements, available explanations, limitations and result-dependent conclusions. Uncomputed values remain absent.</div>
    <StudioPanel title="Measured model records" description="Model results below are rendered only when returned by the backend.">{result.data.models.length ? result.data.models.map(model => <article className="studio-model-record" key={model.id}><header><div><h3>{modelLabels[model.model_type]} <small>Model {shortId(model.id)}</small></h3><Status value={model.status}/></div><Link to="/comparison">Compare models <ExternalLink size={13} aria-hidden="true"/></Link></header>{model.metrics.test ? <><MetricGrid metrics={model.metrics.test}/><ConfusionMatrix metrics={model.metrics.test}/><p>Final training: {seconds(model.metrics.timing?.final_training_seconds)}. Full cross-validation: {seconds(model.metrics.timing?.cv_total_seconds)}. Test inference: {seconds(model.metrics.timing?.test_inference_seconds)}.</p><JsonView value={model.metrics.validation} label="Cross-validation folds, mean and sample standard deviation"/><JsonView value={model.metrics.training} label="Training resubstitution performance (not validation)"/><JsonView value={model.metrics.calibration} label="Probability calibration diagnostics"/></> : <Empty>This model has no completed measurements.</Empty>}<JsonView value={model.details} label="Model identity, provenance, preprocessing, quantum configuration and limitations"/></article>) : <StudioUnavailable title="No model records are available">Model records appear after training finishes or a model failure is recorded.</StudioUnavailable>}</StudioPanel><StudioPanel title="Related research stages" description="These links navigate to real environments; they do not imply that a stage has completed."><StudioNextLinks/><div className="studio-related-links"><Link to="/datasets">Data Lab / Datasets</Link><Link to="/quantum">Quantum Lab / Circuit</Link></div></StudioPanel></>}
  </ResearchStudioPage>;
}
