import {ArrowRight, Microscope, Play} from 'lucide-react';
import {Link} from 'react-router-dom';
import {useState} from 'react';
import {api} from '../services/api';
import {useAction, useLoad} from '../hooks/useLoad';
import type {Explanation, ModelRecord} from '../types';
import {ErrorNotice, Field, JsonView, ModelPicker} from '../components/Common';
import {BarChart} from '../components/Charts';
import {dateTime, seconds} from '../utils/format';
import {ModelLabModelContext, ModelLabNote, ModelLabPage, ModelLabPanel, ModelLabResultHeader, ModelLabUnavailable} from '../components/ModelLab';
export default function Explainability() {
  const [id, setId] = useState(''); const [method, setMethod] = useState('permutation'); const [samples, setSamples] = useState(8); const [repeats, setRepeats] = useState(3); const [maxFeatures, setMaxFeatures] = useState(30);
  const action = useAction(); const model = useLoad<ModelRecord | null>(() => id ? api.get(`/models/${id}`) : Promise.resolve(null), [id]); const explanations = useLoad<Explanation[]>(() => id ? api.get(`/models/${id}/explanations`) : Promise.resolve([]), [id]);
  const [selected, setSelected] = useState<Explanation>(); const quantum = ['vqc', 'qsvc', 'qnn'].includes(model.data?.model_type || ''); const activeMethod = quantum ? 'perturbation' : method; const current = selected?.model_id === id ? selected : explanations.data?.[0];
  async function run() {const value = await action.run(() => api.post<Explanation>(`/models/${id}/explain`, {method: activeMethod, max_samples: samples, repeats, max_features: maxFeatures})); if (value) {setSelected(value); explanations.reload();}}
  return <ModelLabPage currentPath="/explainability" step="03 / EXPLAIN" title="Explainability" description="Inspect measured model behavior without confusing feature influence with medical causation or clinical validity." actions={<Link className="button secondary" to="/prediction"><ArrowRight size={14} aria-hidden="true"/> Continue to Prediction</Link>}>
    <ModelPicker value={id} onChange={setId}/><ModelLabModelContext model={model.data} loading={model.loading}/><ErrorNotice message={action.error || model.error || explanations.error}/>
    <ModelLabPanel title="Explanation method" description="Run a bounded post-hoc analysis for a completed model."><div className="model-lab-stage-icon"><Microscope size={17} aria-hidden="true"/></div><div className="form-grid"><Field label="Method"><select value={activeMethod} disabled={quantum} onChange={e => setMethod(e.target.value)}><option value="permutation">Permutation importance / ROC-AUC decrease</option><option value="shap">Approximate SHAP / numeric-only complete inputs</option><option value="perturbation">Feature perturbation / sensitivity analysis</option></select></Field><Field label="Maximum held-out samples"><input type="number" min={2} max={32} value={samples} onChange={e => setSamples(Number(e.target.value))}/></Field><Field label="Permutation / SHAP repeats"><input type="number" min={1} max={10} disabled={activeMethod === 'perturbation'} value={repeats} onChange={e => setRepeats(Number(e.target.value))}/></Field><Field label="Maximum perturbed features"><input type="number" min={1} max={60} disabled={activeMethod !== 'perturbation'} value={maxFeatures} onChange={e => setMaxFeatures(Number(e.target.value))}/></Field></div><ModelLabNote tone={quantum ? 'quantum' : 'neutral'}>{quantum ? 'Quantum explanation uses observed prediction changes under feature perturbation. It is not a complete interpretation of circuit internals.' : 'Training-only background data is used. Correlation, off-manifold perturbations and small explanation subsets limit interpretation.'}</ModelLabNote><button disabled={!id || action.busy} onClick={() => void run()}><Play size={15} aria-hidden="true"/>{action.busy ? 'Calculating feature influence…' : 'Calculate explanation'}</button></ModelLabPanel>
    <ModelLabPanel title="Measured feature influence" description="The chart is rendered only from the selected explanation response.">{action.busy ? <p className="loading-state" role="status">Calculating measured explanation…</p> : current ? <><ModelLabResultHeader label="EXPLANATION">{current.result.title}</ModelLabResultHeader><p>{current.result.scope}</p><p>{current.result.sample_count} explained samples / {seconds(current.result.elapsed_seconds)} / {dateTime(current.created_at)}</p><p>{current.result.units}</p><BarChart label="Measured model feature influence" items={current.result.influence.slice(0, 30).map(i => ({name: i.feature, value: i.magnitude}))}/><JsonView value={current.result} label="Full measured influence and limitations"/></> : <ModelLabUnavailable title="No explanation has been calculated">Select a completed model and request an explanation to inspect real feature influence.</ModelLabUnavailable>}</ModelLabPanel>
  </ModelLabPage>;
}
