import {ArrowRight, Calculator} from 'lucide-react';
import {Link} from 'react-router-dom';
import {useDraft} from '../hooks/ExperimentDraft';
import {usePreview} from '../hooks/usePreview';
import {DatasetPicker, ErrorNotice, Field, useActiveDataset} from '../components/Common';
import {BarChart} from '../components/Charts';
import type {PipelineConfig} from '../types';
import {DataLabDatasetContext, DataLabNote, DataLabFeatureIcon, DataLabPage, DataLabPanel, DataLabUnavailable} from '../components/DataLab';
export default function FeatureSelection() {
  const {draft, pipeline} = useDraft(); const dataset = useActiveDataset(); const result = usePreview('/feature-selection/preview'); const p = draft.pipeline;
  const scored = result.preview?.selection_scores.filter(s => s.score !== null).sort((a, b) => (b.score || 0) - (a.score || 0)).slice(0, 20) ?? [];
  return <DataLabPage currentPath="/features" step="04 / SELECT" title="Feature selection" description="Select reproducible model inputs without leaking labels or turning a benchmark score into a biological claim." actions={<button disabled={!draft.dataset_id || result.busy} onClick={() => void result.refresh()}><Calculator size={15} aria-hidden="true"/>{result.busy ? 'Calculating…' : 'Calculate selection'}</button>}>
    <DatasetPicker/><DataLabDatasetContext dataset={dataset.data} loading={dataset.loading} error={dataset.error}/><ErrorNotice message={dataset.error || result.error}/>
    <DataLabPanel title="Selection configuration" description="The backend computes selection statistics within the configured training pipeline."><DataLabFeatureIcon kind="selection"/><div className="form-grid"><Field label="Method"><select value={p.selection} onChange={e => pipeline({selection: e.target.value as PipelineConfig['selection']})}><option value="none">No selection</option><option value="anova">ANOVA F score</option><option value="mutual_info">Mutual information</option><option value="variance">Variance threshold</option></select></Field><Field label="Maximum retained features" help="ANOVA / mutual information: capped at available encoded dimensions."><input type="number" min={1} max={400} value={p.k_features} onChange={e => pipeline({k_features: Number(e.target.value)})}/></Field><Field label="Variance threshold" help="Applied after the configured encoding and scaling stages."><input type="number" min={0} max={10} step="0.001" value={p.variance_threshold} onChange={e => pipeline({variance_threshold: Number(e.target.value)})}/></Field></div><DataLabNote tone="research">Selection scores are not medical feature importance. A feature selected on this benchmark does not establish biological causation.</DataLabNote></DataLabPanel>
    {result.preview ? <div className="two-columns"><DataLabPanel title="Training selection scores" description="Only scores returned by the backend are shown."><BarChart label="Training-only feature selection scores" items={scored.map(s => ({name: s.feature, value: s.score!}))}/></DataLabPanel><DataLabPanel title="Retained encoded features" description="The returned feature set before PCA."><div className="data-lab-result-header"><span>FEATURES RETAINED</span><strong>{result.preview.selected_features.length}</strong></div><div className="chip-list">{result.preview.selected_features.map(f => <span className="chip" key={f}>{f}</span>)}</div><p>Fold-specific rankings may differ. The same procedure and partitions apply to all compared models.</p><Link to="/pca" className="button secondary">Continue to PCA <ArrowRight size={14} aria-hidden="true"/></Link></DataLabPanel></div> : <DataLabPanel title="Selection result" description="Request a real training-only selection preview to inspect returned scores.">{result.busy ? <p className="loading-state" role="status">Calculating training-only selection…</p> : <DataLabUnavailable title="No feature-selection output yet">The workspace will show a ranked view only when the backend returns real selection scores.</DataLabUnavailable>}</DataLabPanel>}
  </DataLabPage>;
}
