import {ArrowRight, Orbit} from 'lucide-react';
import {Link} from 'react-router-dom';
import {useDraft} from '../hooks/ExperimentDraft';
import {usePreview} from '../hooks/usePreview';
import {DatasetPicker, ErrorNotice, Field, JsonView, useActiveDataset} from '../components/Common';
import {BarChart} from '../components/Charts';
import {metric} from '../utils/format';
import {DataLabDatasetContext, DataLabNote, DataLabFeatureIcon, DataLabPage, DataLabPanel, DataLabResultHeader, DataLabUnavailable} from '../components/DataLab';
export default function PCA() {
  const {draft, pipeline} = useDraft(); const dataset = useActiveDataset(); const result = usePreview('/pca/preview'); const p = draft.pipeline;
  return <DataLabPage currentPath="/pca" step="05 / REDUCE" title="PCA / dimensions" description="Fit a compact representation on training data before classical and quantum learning, while keeping held-out evaluation separate." actions={<button disabled={!draft.dataset_id || result.busy} onClick={() => void result.refresh()}><Orbit size={15} aria-hidden="true"/>{result.busy ? 'Fitting PCA…' : 'Calculate PCA'}</button>}>
    <DatasetPicker/><DataLabDatasetContext dataset={dataset.data} loading={dataset.loading} error={dataset.error}/><ErrorNotice message={dataset.error || result.error}/>
    <DataLabPanel title="PCA configuration" description="Configuration is local draft state until a real backend preview is requested."><DataLabFeatureIcon kind="pca"/><div className="form-grid"><Field label="PCA components" help="For quantum comparisons this must equal the qubit count. Keep within training sample and selected feature dimensions."><input type="number" min={1} max={100} disabled={p.pca_components === null} value={p.pca_components ?? 4} onChange={e => pipeline({pca_components: Number(e.target.value)})}/></Field><label className="check"><input type="checkbox" checked={p.pca_components !== null} onChange={e => pipeline({pca_components: e.target.checked ? 4 : null})}/>Enable PCA</label><label className="check"><input type="checkbox" checked={p.pca_whiten} onChange={e => pipeline({pca_whiten: e.target.checked})}/>Whiten principal components</label></div><DataLabNote tone="research">Explained variance measures the fitted representation, not disease-prediction accuracy. Quantum and classical comparators share this representation.</DataLabNote></DataLabPanel>
    <DataLabPanel title="Training representation" description="The visualization below is rendered from the backend response only.">{result.preview ? <><DataLabResultHeader label="RETAINED VARIANCE">{result.preview.pca_explained_variance.length ? metric(result.preview.pca_explained_variance.reduce((a, b) => a + b, 0)) : 'PCA disabled'}</DataLabResultHeader><BarChart percent label="Training principal-component explained variance" items={result.preview.pca_explained_variance.map((value, index) => ({name: `PC${index + 1}`, value}))}/><JsonView value={{columns: result.preview.selected_features, loadings_by_component: result.preview.pca_loadings}} label="PCA component loadings"/><p className="mono wrap">Partition fingerprint: {result.preview.split_hash}</p><Link to="/training" className="button secondary">Continue to Model Lab <ArrowRight size={14} aria-hidden="true"/></Link></> : result.busy ? <p className="loading-state" role="status">Fitting training-only PCA…</p> : <DataLabUnavailable title="No PCA result yet">Calculate a real backend preview to inspect explained variance and component loadings.</DataLabUnavailable>}</DataLabPanel>
  </DataLabPage>;
}
