import {ArrowRight, Play, SlidersHorizontal} from 'lucide-react';
import {Link} from 'react-router-dom';
import {useDraft} from '../hooks/ExperimentDraft';
import {usePreview} from '../hooks/usePreview';
import {DatasetPicker, ErrorNotice, Field, JsonView, useActiveDataset} from '../components/Common';
import type {PipelineConfig} from '../types';
import {DataLabDatasetContext, DataLabNote, DataLabPage, DataLabPanel, DataLabResultHeader, DataLabUnavailable} from '../components/DataLab';
export default function Preprocessing() {
  const {draft, update, pipeline} = useDraft(); const dataset = useActiveDataset(); const result = usePreview(); const p = draft.pipeline;
  const features = dataset.data?.provenance.features || [], selected = draft.features || features, numeric = dataset.data?.provenance.numeric_features || [];
  function ratioField(index: number, key: 'name' | 'numerator' | 'denominator', value: string) {pipeline({ratios: p.ratios.map((r, i) => i === index ? {...r, [key]: value} : r)});}
  return <DataLabPage currentPath="/preprocessing" step="03 / PREPARE" title="Preprocessing" description="Configure leakage-safe transformations that are learned from training data and carried into every comparison." actions={<button disabled={result.busy || !draft.dataset_id} onClick={() => void result.refresh()}><Play size={15} aria-hidden="true"/>{result.busy ? 'Fitting preview…' : 'Preview pipeline'}</button>}>
    <DatasetPicker/><DataLabDatasetContext dataset={dataset.data} loading={dataset.loading} error={dataset.error}/><ErrorNotice message={dataset.error || result.error}/>
    <div className="two-columns"><DataLabPanel title="Input schema" description="Choose the feature columns that enter the reproducible training pipeline."><Field label="Selected input features" help="The target is excluded automatically. Review identifiers and target proxies in Data Quality."><select multiple size={12} value={selected} onChange={e => update({features: Array.from(e.target.selectedOptions, o => o.value)})}>{features.map(f => <option key={f} value={f}>{f}</option>)}</select></Field><button className="secondary" onClick={() => update({features: null})}>Use all non-target features</button><p>{selected.length} selected features. Target: {dataset.data?.provenance.target || 'Not selected'}.</p><Link to="/quality" className="text-link">Review quality diagnostics <ArrowRight size={13} aria-hidden="true"/></Link></DataLabPanel>
      <DataLabPanel title="Transformations" description="Training-only parameters keep preprocessing separate from held-out evaluation."><div className="form-grid"><Field label="Numeric missing-value strategy"><select value={p.imputer} onChange={e => pipeline({imputer: e.target.value as PipelineConfig['imputer']})}><option value="median">Median</option><option value="mean">Mean</option><option value="most_frequent">Most frequent</option></select></Field><Field label="Scaling"><select value={p.scaler} onChange={e => pipeline({scaler: e.target.value as PipelineConfig['scaler']})}>{['standard', 'minmax', 'robust', 'none'].map(v => <option value={v} key={v}>{v}</option>)}</select></Field><Field label="Outlier strategy"><select value={p.outlier_strategy} onChange={e => pipeline({outlier_strategy: e.target.value as PipelineConfig['outlier_strategy']})}><option value="none">Retain observations</option><option value="clip_quantiles">Clip using training quantiles</option></select></Field><Field label="Duplicate records"><select value={draft.duplicate_policy} onChange={e => update({duplicate_policy: e.target.value as 'reject' | 'drop_exact'})}><option value="reject">Reject before split</option><option value="drop_exact">Explicitly drop exact duplicates</option></select></Field><Field label="Lower clipping quantile"><input type="number" min="0" max="0.49" step="0.01" value={p.lower_quantile} onChange={e => pipeline({lower_quantile: Number(e.target.value)})}/></Field><Field label="Upper clipping quantile"><input type="number" min="0.51" max="1" step="0.01" value={p.upper_quantile} onChange={e => pipeline({upper_quantile: Number(e.target.value)})}/></Field></div><DataLabNote><SlidersHorizontal size={15} aria-hidden="true"/>Categorical features use training-fitted most-frequent imputation and bounded one-hot encoding. Unseen categories are ignored by the encoder.</DataLabNote><label className="check"><input type="checkbox" checked={p.angle_scaling} onChange={e => pipeline({angle_scaling: e.target.checked})}/>Apply shared training-fitted angle scaling to [0, pi] for every compared model.</label></DataLabPanel></div>
    <DataLabPanel title="Feature engineering" description="Optional transformations are represented in the pipeline configuration and are not executed until the backend preview is requested."><Field label="Optional log1p transforms" help="Select only nonnegative numeric features. Ratios are calculated on original values before log transforms."><select multiple size={5} value={p.log_features} onChange={e => pipeline({log_features: Array.from(e.target.selectedOptions, o => o.value)})}>{numeric.filter(f => selected.includes(f)).map(f => <option key={f} value={f}>{f}</option>)}</select></Field>{p.ratios.map((r, i) => <div className="ratio-row" key={i}><Field label="New feature name"><input value={r.name} onChange={e => ratioField(i, 'name', e.target.value)}/></Field>{(['numerator', 'denominator'] as const).map(key => <Field label={key} key={key}><select value={r[key]} onChange={e => ratioField(i, key, e.target.value)}><option value="">Select feature</option>{numeric.filter(f => selected.includes(f)).map(f => <option key={f} value={f}>{f}</option>)}</select></Field>)}<button className="ghost" onClick={() => pipeline({ratios: p.ratios.filter((_, j) => j !== i)})}>Remove</button></div>)}<button className="secondary" disabled={p.ratios.length >= 20} onClick={() => pipeline({ratios: [...p.ratios, {name: `ratio_${p.ratios.length + 1}`, numerator: '', denominator: ''}]})}>Add ratio feature</button></DataLabPanel>
    <DataLabPanel title="Pipeline preview" description="A preview is available only after the existing backend endpoint returns a result.">{result.preview ? <><DataLabResultHeader label="BACKEND PREVIEW">{result.preview.train_count} training / {result.preview.test_count} held-out samples</DataLabResultHeader><p>{result.preview.output_features.length} output dimensions</p><p className="workflow-ribbon">{result.preview.stages.join(' / ')}</p><JsonView value={result.preview} label="Preview metadata, selection scores and PCA loadings"/></> : result.busy ? <p className="loading-state" role="status">Fitting training-only preview…</p> : <DataLabUnavailable title="No preprocessing result yet">Configure the pipeline above, then request a real backend preview. No progress or output is simulated in the interface.</DataLabUnavailable>}</DataLabPanel>
  </DataLabPage>;
}
