import {useEffect, useState} from 'react';
import {ArrowRight, ShieldCheck} from 'lucide-react';
import {Link} from 'react-router-dom';
import {api} from '../services/api';
import {useAction} from '../hooks/useLoad';
import {useDraft} from '../hooks/ExperimentDraft';
import {DatasetPicker, Empty, ErrorNotice, JsonView, useActiveDataset} from '../components/Common';
import {BarChart} from '../components/Charts';
import {DataLabDatasetContext, DataLabNote, DataLabPage, DataLabPanel, DataLabResultHeader} from '../components/DataLab';
import type {Quality as QualityResult} from '../types';
export default function Quality() {
  const {draft} = useDraft(); const dataset = useActiveDataset(); const action = useAction(); const [checked, setChecked] = useState<QualityResult>();
  useEffect(() => setChecked(undefined), [draft.dataset_id, draft.features]);
  const quality = checked || dataset.data?.quality;
  async function validate() {const q = await action.run(() => api.post<QualityResult>(`/datasets/${draft.dataset_id}/validate`, {features: draft.features})); if (q) setChecked(q);}
  return <DataLabPage currentPath="/quality" step="02 / VALIDATE" title="Data quality" description="Inspect structure, target validity, class balance and potential leakage before preparing model inputs." actions={<button disabled={!draft.dataset_id || action.busy} onClick={() => void validate()}><ShieldCheck size={16} aria-hidden="true"/>{action.busy ? 'Checking…' : 'Validate selected inputs'}</button>}>
    <DatasetPicker/><DataLabDatasetContext dataset={dataset.data} loading={dataset.loading} error={dataset.error}/><ErrorNotice message={dataset.error || action.error}/>
    {quality ? <><div className="two-columns"><DataLabPanel title="Quality overview" description="Aggregate diagnostics returned by the selected dataset validation."><DataLabResultHeader label="SCOPE">{quality.scope}</DataLabResultHeader><div className="metric-grid"><div className="metric primary-metric"><span>SAMPLES</span><strong>{quality.row_count}</strong><small>Rows in the evaluated dataset</small></div><div className="metric"><span>FEATURES</span><strong>{quality.feature_count}</strong><small>Reviewed input features</small></div><div className="metric"><span>MINORITY FRACTION</span><strong>{quality.minority_fraction}</strong><small>Backend-reported class proportion</small></div><div className="metric"><span>CLASS BALANCE</span><strong>{quality.class_imbalance ? 'Review' : 'No flag'}</strong><small>Backend quality result</small></div></div><BarChart label="Observed target class counts" items={Object.entries(quality.class_distribution).map(([name, value]) => ({name, value}))}/></DataLabPanel><DataLabPanel title="Quality gates" description="Warnings and blockers are reported by the backend checks.">{quality.blockers.length ? quality.blockers.map(w => <ErrorNotice message={w} key={w}/>) : <DataLabNote tone="research">No blocking issue was found by these automated checks. This is not a guarantee of data suitability.</DataLabNote>}{quality.warnings.map(w => <p className="warning-text" key={w}>{w}</p>)}<p>Exact duplicate rows: <b>{quality.duplicate_rows}</b>. Duplicate feature vectors: <b>{quality.duplicate_feature_rows}</b>.</p><Link to="/preprocessing" className="button secondary">Continue to preprocessing <ArrowRight size={14} aria-hidden="true"/></Link></DataLabPanel></div>
      <div className="two-columns"><DataLabPanel title="Missing and infinite values" description="Raw counts by feature; no frontend thresholds are applied."><div className="table-scroll"><table><caption>Numeric integrity by feature</caption><thead><tr><th scope="col">Feature</th><th scope="col">Missing</th><th scope="col">Infinite</th></tr></thead><tbody>{Object.keys(quality.missing_values).map(name => <tr key={name}><td>{name}</td><td>{quality.missing_values[name]}</td><td>{quality.infinite_values[name] ?? 'Not evaluated'}</td></tr>)}</tbody></table></div><p>{quality.invalid_numeric_values}</p></DataLabPanel><DataLabPanel title="Potential proxies and redundancy" description="Signals requiring researcher review, reported by the quality analysis."><h3>Potential identifiers</h3><p>{quality.identifier_features.join(', ') || 'None detected by the name-based heuristic.'}</p><h3>Suspiciously predictive features</h3><p>{quality.suspiciously_predictive_features.join(', ') || 'None detected by the near-perfect target-proxy heuristic.'}</p><h3>Constant features</h3><p>{quality.constant_features.join(', ') || 'None detected.'}</p><JsonView value={quality.highly_correlated_pairs} label="Highly correlated feature pairs"/><JsonView value={quality.distributions} label="Aggregate feature distributions"/></DataLabPanel></div></> : <DataLabPanel title="Quality diagnostics" description="Select a dataset to inspect its quality report.">{dataset.loading ? <p className="loading-state" role="status">Loading quality context…</p> : <Empty>Select a dataset to inspect its quality.</Empty>}</DataLabPanel>}
    <DataLabNote>Quality diagnostics describe the current dataset and selected features. They do not establish clinical validity or model performance.</DataLabNote>
  </DataLabPage>;
}
