import {ArrowRight, Atom, Play} from 'lucide-react';
import {Link} from 'react-router-dom';
import {useState} from 'react';
import {api} from '../services/api';
import {useAction, useLoad} from '../hooks/useLoad';
import {useDraft} from '../hooks/ExperimentDraft';
import type {Circuit} from '../types';
import {ErrorNotice, Field, JsonView, ModelPicker} from '../components/Common';
import {CircuitDiagram} from '../components/Charts';
import QuantumSettings from '../components/QuantumSettings';
import {QuantumBackendState, QuantumCircuitContext, QuantumLabPage, QuantumNote, QuantumPanel, QuantumSettingsMark} from '../components/QuantumLab';
export default function QuantumCircuit() {
  const {draft} = useDraft(); const action = useAction(); const [kind, setKind] = useState<'vqc' | 'qsvc' | 'qnn'>('vqc'); const [modelId, setModelId] = useState(''); const [circuit, setCircuit] = useState<Circuit>();
  const capabilities = useLoad<{available: boolean; runtime_verified: boolean; execution: string}>(() => api.get('/quantum/capabilities'));
  async function preview() {const value = await action.run(() => api.post<Circuit>('/quantum/circuit', {quantum: draft.quantum, model_type: kind, seed: draft.seed})); if (value) setCircuit(value);}
  async function registered() {const value = await action.run(() => api.get<Circuit>(`/models/${modelId}/circuit`)); if (value) setCircuit(value);}
  return <QuantumLabPage currentPath="/quantum" step="01 / CIRCUIT" title="Quantum circuit" description="Inspect the structural representation used by supported quantum and hybrid models. This view does not execute a circuit or imply hardware performance." actions={<Link className="button secondary" to="/training"><ArrowRight size={14} aria-hidden="true"/> Configure in Model Lab</Link>}>
    <QuantumBackendState available={capabilities.data?.available} runtimeVerified={capabilities.data?.runtime_verified} execution={capabilities.data?.execution}/><QuantumCircuitContext circuit={circuit}/><ErrorNotice message={action.error || capabilities.error}/>
    <div className="two-columns"><QuantumPanel title="Parameterized circuit preview" description="Generate a backend-described circuit for the selected supported model."><QuantumSettingsMark/><Field label="Quantum model"><select value={kind} onChange={e => setKind(e.target.value as 'vqc' | 'qsvc' | 'qnn')}><option value="vqc">VQC: feature map + ansatz</option><option value="qsvc">QSVC: kernel feature map</option><option value="qnn">QNN: sampler neural network</option></select></Field><QuantumSettings/><button disabled={action.busy || capabilities.data?.available === false} onClick={() => void preview()}><Play size={15} aria-hidden="true"/>{action.busy ? 'Generating representation…' : 'Generate circuit representation'}</button><QuantumNote tone="warning">This endpoint describes a parameterized logical circuit. It does not execute a simulator, retrieve hardware timing, or measure quantum advantage.</QuantumNote></QuantumPanel><QuantumPanel title="Registered quantum model" description="Retrieve the stored circuit metadata for a completed quantum model."><ModelPicker quantumOnly value={modelId} onChange={setModelId}/><button disabled={!modelId || action.busy} onClick={() => void registered()}>Retrieve registered circuit</button><QuantumNote tone="research">QNN, VQC and QSVC remain backend-supported model types. Their circuit structures and limitations are returned by the backend.</QuantumNote></QuantumPanel></div>
    {circuit ? <QuantumPanel title={`${circuit.model_type.toUpperCase()} / ${circuit.execution_kind}`} description="Structural circuit metadata returned by the backend."><div className="circuit-stats"><span className="mono"><b>{circuit.qubits}</b> qubits</span><span className="mono"><b>{circuit.logical_depth}</b> logical depth</span><span className="mono"><b>{circuit.parameter_count}</b> parameters</span></div><CircuitDiagram circuit={circuit}/><QuantumNote>{circuit.limitation}</QuantumNote><details><summary>Full text circuit</summary><pre className="circuit-text">{circuit.text}</pre></details><JsonView value={circuit.gate_counts} label="Gate counts"/></QuantumPanel> : <QuantumPanel title="Circuit result" description="The structural viewer will appear after a real backend response."><div className="quantum-empty"><Atom size={22} aria-hidden="true"/><strong>{action.busy ? 'Generating circuit representation…' : 'No circuit representation yet'}</strong><p>Configure a supported quantum model and request a preview. No circuit execution or measurement is simulated in this page.</p></div></QuantumPanel>}
  </QuantumLabPage>;
}
